Fix error on quantities when exist multiple organizations
adempiere/adempiere pull request #3311
Opened 2021-01-13 13:36 UTC by Ganzt90

Fixed error on quantities to replenish on Smart Browser Warehouse Replenish

2021-01-13 13:52 UTC, marcalwestf commented
@Ganzt90  thnak you for your valuable contribution.

To help us review your changes easier and thus accept them earlier, it would be nice if you coud upload some screenshots before and after your changes. Otherwise we have to figure out the whole process.

Thanks!!

2021-01-13 14:41 UTC, yamelsenih requested changes
Hi @Ganzt90 please fix it and add a step by step with a gif

2021-01-13 14:41 UTC, yamelsenih commented on migration/393lts-394lts/7130_UpdateReplenishView.xml
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?>
Please change file name to 07130

2021-01-14 18:44 UTC, Ganzt90 commented
The following example shows what happens:

- Product: Bag50_Bag 50 Kg

Replenishment is configured, Maintain at maximum level in the HQ Warehouse, maximum level 40.00 minimum level 10.00.
The same configuration is done for the Store West warehouse.

![image](https://user-images.githubusercontent.com/37981079/104618287-e002dd80-5662-11eb-8e1a-f996168b663f.png)

![image](https://user-images.githubusercontent.com/37981079/104618315-e85b1880-5662-11eb-957d-42673084b1f3.png)


When generating the Storage Detail reports it is observed that the Product has existence in the warehouse of the HQ organization and while it does not have existence in the warehouse of the Store West organization

![image](https://user-images.githubusercontent.com/37981079/104617465-d88f0480-5661-11eb-9fb0-2bbbec357c90.png)

Consulting the smartbrowser Warehouse Replenish for the HQ Warehouse and Store West warehouses, the following is obtained:

![Error on SBReplenish](https://user-images.githubusercontent.com/37981079/104618633-569fdb00-5663-11eb-93cb-4b62c8817b83.gif)

- The quantity to order in the HQ Warehouse of 12.
- The quantity to order in the Store West Warehouse of 12, where the correct thing for this warehouse should be 40 since the warehouse does not have the product in stock.

After correcting the SQL View of the Warehouse Replenishment Smartbrowser the following result is obtained:

![Fixed Query on SBReplenish](https://user-images.githubusercontent.com/37981079/104631443-a0dc8880-5672-11eb-8060-33eaee163f64.gif)

2021-01-23 19:12 UTC, marcalwestf commented
@Ganzt90  I loaded and executed the XML.
When I try to apply it, there are two errors:

> org.adempiere.exceptions.AdempiereException: Migration 7130 - Update Replenish View - 3.9.4 (ECA02) ; Step: 20; Type: SQL.  Application failed. 
> org.postgresql.util.PSQLException: Unterminated block comment started at position 0 in SQL /******************************************************************************
>  * Product: Adempiere ERP & CRM Smart Business Solution                       *
>  * This program is free software. Expected */ sequence
> 	at org.compiere.model.MMigration.apply(MMigration.java:178)
> 	at org.compiere.model.MMigration.apply(MMigration.java:176)

This error can be avoided by eliminating the java comments.

If the java comments are deleted, another error is thrown:

> Migration 7130 - Update Replenish View - 3.9.4 (ECA02) ; Step: 20; Type: SQL. Application failed. org.postgresql.util.PSQLException: ERROR: column s.m_warehouse_id does not exist
> 
> GROUP BY s.M_Product_ID) s ON(s.M_Product_ID = p.M_Product_ID AND s.M_Warehouse_ID=r_1.M_Warehouse_ID)
> Hint: Perhaps you meant to reference the column "r.m_warehouse_id". Position: 3207

Looking at the SQL, Relation "s" has no warehouse_id defined nor it is included in the GROPU BY clause; and also relation "r_1" doesn't exist.

Changing it as follows works, but I don't know if it is syntactically correct:
   

>  LEFT JOIN (SELECT s.M_Product_ID, 
>                 SUM(s.QtyOnHand) AS QtyOnHand, 
>                 SUM(s.QtyOrdered) AS QtyOrdered, 
>                 SUM(s.QtyReserved) AS QtyReserved, 
>                 SUM(s.QtyAvailable) AS QtyAvailable,
>                 M_Warehouse_ID 
>             FROM RV_Storage s
>             GROUP BY s.M_Product_ID, s.M_Warehouse_ID) s ON(s.M_Product_ID = p.M_Product_ID AND s.M_Warehouse_ID=r.M_Warehouse_ID)

2021-01-28 13:53 UTC, marcalwestf commented
hi @Ganzt90 Germán, could you please modify the sequence no so it displays the same number as the XML file?
![Selection_993](https://user-images.githubusercontent.com/1789408/106143533-87d6db80-6138-11eb-89b8-7eac660764ac.png)

Thanks!

2021-01-28 13:57 UTC, marcalwestf commented
running the _XML 07130_UpdateReplenishView.xml_, I get the following error:
![Selection_994](https://user-images.githubusercontent.com/1789408/106147877-0124fd00-613e-11eb-8b35-dc0c47de6812.png)


... and looking at the SQL, the culprit is:
![Selection_995](https://user-images.githubusercontent.com/1789408/106148212-67118480-613e-11eb-8233-3436cade47a5.png)

2021-01-28 14:20 UTC, marcalwestf commented
@Ganzt90  the column _isActive_ is not defined for relation "r".
If you change instead "rep" for "r", the SQL works and the replenish report also.
![Selection_996](https://user-images.githubusercontent.com/1789408/106150329-d9836400-6140-11eb-931b-b909c3425b5e.png)

2021-01-29 19:19 UTC, marcalwestf approved these changes
1. Checked, loaded, and executed XML file **from console** (with _RUN_MigrateXML.sh_).
2. View was modified accordingly.
3. Ran tests as described.
4. Error was corrected.
Test passed.

2021-01-29 19:21 UTC, merged