#3267 Validate Ordered and Reserved Quantities Inventory https://git…
adempiere/adempiere pull request #3342
Opened 2021-01-26 20:21 UTC by e-Evolution

…hub.com/adempiere/adempiere/issues/3267

(cherry picked from commit 549f663d115313163456932b9c34bcaedfb169ed)

2021-01-28 15:11 UTC, yamelsenih commented
I see that this PR duplicate many changes with this other: #3343
Please keep separated both or maybe I can review it after #3343

2021-01-28 17:35 UTC, e-Evolution commented
> I see that this PR duplicate many changes with this other: #3343
> Please keep separated both or maybe I can review it after #3343

@yamelsenih, Hi Yamel As I put in the description, this pull request depends on the other pull request, and in effect it is separated, that is why there is a dependency, as soon as the first pull request is accepted, you can see here the implementation of only these changes

2021-03-15 10:11 UTC, yamelsenih requested changes

2021-03-15 10:11 UTC, yamelsenih commented on base/src/org/adempiere/engine/StorageEngine.java
> +	public static void createTransaction(
Please make this code more atomic, the refactory can be change in other pull request as Source code Improve

2021-03-18 21:16 UTC, yamelsenih requested changes

2021-03-18 21:16 UTC, yamelsenih commented on migration/393lts-394lts/06430_ValidateOrderedAndReservedQuantity.xml
> +  <Migration EntityType="D" Name="Validate Ordered and Reserved Quantity" ReleaseNo="" SeqNo="6430">
Please set Release No to 3.9.4

2021-03-18 21:16 UTC, yamelsenih commented on migration/393lts-394lts/06430_ValidateOrderedAndReservedQuantity.xml
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?>
Change File no and sequence to last

2021-03-18 21:19 UTC, yamelsenih commented
for last I think that is good add the follows filters:
- Product Category
- Product Group
- Product Class
- Product Classification

![Screenshot_20210318_171508](https://user-images.githubusercontent.com/2333092/111699153-21a03800-880e-11eb-9ac5-5645668f0053.png)


What is the reason?
When a installed App have many movements and SKU's is very slow this process, also exists more way for process products

Just add the above changes for merge.

Best regards

2021-03-18 22:50 UTC, e-Evolution commented on migration/393lts-394lts/06430_ValidateOrderedAndReservedQuantity.xml
> +  <Migration EntityType="D" Name="Validate Ordered and Reserved Quantity" ReleaseNo="" SeqNo="6430">
Fixed adding the 3.9.4

2021-04-14 21:18 UTC, yamelsenih commented
I was merged this PR #3343 but the changes are many here. Can you update the heades of this PR?
Also, can you paste a image or gif with the changes requested for me?

Best regards

2021-04-15 21:29 UTC, yamelsenih commented
Hi @e-Evolution I am seeing the process. I think tha tis nice to have as no mandatory the organization
![Screenshot_20210415_172852](https://user-images.githubusercontent.com/2333092/114940681-2dcce480-9e10-11eb-8e3f-1ab4bbb889de.png)

2021-04-15 21:33 UTC, yamelsenih commented
Aso you should remove unused imports like
```Java
import org.compiere.util.Msg;
```

2021-04-15 21:51 UTC, e-Evolution commented
> Aso you should remove unused imports like
> 
> ```java
> import org.compiere.util.Msg;
> ```

The import class was fixed

2021-04-22 17:55 UTC, yamelsenih commented
>Hi @e-Evolution I am seeing the process. I think tha tis nice to have as no mandatory the organization
Hi @e-Evolution I am waiting for this

2021-04-22 22:47 UTC, e-Evolution commented
> > Hi @e-Evolution I am seeing the process. I think tha tis nice to have as no mandatory the organization
> 
> Hi @e-Evolution I am waiting for this

@yamelsenih ready I added the organization as not mandatory

2021-04-22 22:48 UTC, yamelsenih commented
Thanks, I will check it

2021-04-24 19:55 UTC, merged