Improve modification indication UX in Swing editor
adempiere/adempiere pull request #3592
Opened 2021-08-16 23:21 UTC by dram

Instead of indicating that data is modified only when focus is out of editor, this commit try to mark modification immediately after text in editor is changed.

With this change, user can type <F4> or click Save icon directly to save data after text editing is finished, without having to move focus out of editor.

BTW: I have only tested VString and VText, not sure where VMemo is used, may someone give me a hint?

2021-08-28 05:09 UTC, dram commented
Hi @marcalwestf , I have added two gif screencasts, hope this helps.

2021-08-28 13:46 UTC, marcalwestf commented
@dram  thanks a lot.
Now it is very clear!
I think it will be soon tested.

2021-08-31 17:24 UTC, marcalwestf commented
@dram  in table _AD_Rule_, column _Script_, you find a memo:
![image](https://user-images.githubusercontent.com/1789408/131548096-ac259fdd-e6e4-4c72-8712-cd57db1629f7.png)

2021-08-31 17:39 UTC, marcalwestf commented
1. Tested as described a grid containing text. 
    Fields: _Search Key_, _Name_, _Description_, _Comment/Help_.
    Work as described: changes in grid as soon as a key is hit.
2. Change field _Script_ on window _Rule_:
![20210831_ChangeMemo](https://user-images.githubusercontent.com/1789408/131549179-7dd3806b-4a2d-439c-86bc-e651a1c6b70d.gif)

2021-08-31 17:50 UTC, marcalwestf commented
3. Change memo field on grid: changes are OK, but when you switch back to the single line view, it forgets the change.
    This happens also with the other types. I will post a gif this regarding.
![20210831_ChangeMemo2](https://user-images.githubusercontent.com/1789408/131551025-8c0778af-2932-407f-b8f8-fa4b238e0f53.gif)

2021-08-31 17:54 UTC, marcalwestf commented
It seems that switching from single row to grid, the changes are kept, but not the other way around.
![20210831_ChangeText](https://user-images.githubusercontent.com/1789408/131552029-36034c70-81c0-4f75-830e-0e5f2f674479.gif)

2021-08-31 18:03 UTC, marcalwestf commented
@dram  and also another favor please: the changes are done with a different encoding, so that when we compare the changes, we must select "Ignore white spaces" to see them well.
Perhaps you are so kind and make sure the encoding is such that a compare yields directly only changes? Thanks a lot!!!
![20210831_IgnoreWhiteSpaces](https://user-images.githubusercontent.com/1789408/131553260-ebfb780b-12b8-45d0-ac86-dd095c4c4029.gif)

2021-08-31 18:08 UTC, marcalwestf requested changes
- tests went well as described above
- missing just taking changes from grid display to single-row display

2021-09-01 10:10 UTC, dram commented
@marcalwestf thank you for your comprehensive tests!

Regarding to the two problems you mentioned:

1. "missing just taking changes from grid display to single-row display", I think this problem is not related to this PR, as it already exists in current develop branch.
2. file encoding: I think this problem is caused by line endings of those files changed by this PR, which is ended with CRLF, it may cause problem when checking out in Linux systems, so this problem is also not related to this PR.

2021-09-01 15:53 UTC, marcalwestf commented
@dram  
1. "_I think this problem is not related to this PR, as it already exists in current develop branch._".   -> I know. I thought perhaps you'd take it up once you're there  :) 
2.  " _I think this problem is caused by line endings of those files changed by this PR, which is ended with CRLF, it may cause problem when checking out in Linux systems_"  -> Agree 100% with you. 
The solution would be that you keep the files you want to commit in the same way as you find them. In your case, take the files and convert them. As many of us do develop with iOS and Linux, it would be cumbersome if we'd change every time we would need to check changes.

Thanks in advance.

2021-09-01 23:22 UTC, dram commented
Hi @marcalwestf,

I did some more investigation, the change loss problem when toggling between single and multi rows is caused by those lines:

https://github.com/adempiere/adempiere/blob/develop/client/src/org/compiere/grid/GridController.java#L765-L770

If those lines are commented out, it works properly, so it is related to issue #421 , and maybe @mckayERP can have a look at that.

Regarding to the line ending problem, there are two approaches to cope with it:

1. Change all touched files to LF endings, and then do modification based on them.
2. Do not change file endings, in this case, as those files in develop branch are CRLF endings, keep it as is.

Currently, I take the second approach, it should not cause problem with proper git client configs. The problem you mentioned may be caused by that your git client converting all CRLF endings to LF automatically when checking out.

BTW, following are some quick statistics:

```
% find . -name *.java | wc -l
5328
% find . -name *.java -exec file {} \; | grep CRLF | wc -l
1993
```

There are 5k Java sources files, and with almost 2k of them are CRLF endings. With this large number of CRLF ending files, personally, I'd prefer second approach to first one.

2021-09-02 16:31 UTC, marcalwestf commented
@dram  thanks for your elaborate answer.
It seems that actually, there was an automatic change on one of my tools, because when I download the files directly from Github, and compare them with the head revision, only the differences are displayed. 

As soon as the checks are passed, I will merge this PR.

If you wish, and it is not burdensome to you, I can create an issue regarding the switching between single-row and grid and you might create a pull request? I would test it and eventually accept it.
I cannot do the pull request and accept it myself....
Thanks !

2021-09-02 16:35 UTC, marcalwestf approved these changes

2021-09-02 18:30 UTC, merged

2021-09-02 22:02 UTC, dram commented
Hi @marcalwestf , feel free to create an issue, I'll have a look at that problem.