New way to iterate resultsets test m tree
adempiere/adempiere pull request #3724
Opened 2022-02-03 19:28 UTC by rcapecce

Fixes 3723

2022-02-03 19:36 UTC, yamelsenih requested changes

2022-02-03 19:36 UTC, yamelsenih commented on base/src/org/compiere/util/DB.java
> +    public static void runResultSet(String trxName, String query, Object[] parameters, ResultSetRunnable resultSetRunnable) throws SQLException {
Can you declare it `Object[] parameters` as this `Object... parameters` just add at end of parameters and it is a array very dynamic

2022-02-03 20:23 UTC, rcapecce reviewed
Hi @yamelsenih I remove this implementation and use the parammeters to the endo of the signature

2022-02-03 21:14 UTC, rcapecce reviewed
Can you review this new implementation?

2022-03-29 20:21 UTC, e-Evolution commented
This pull request was implement in join with #3735

2022-03-29 20:21 UTC, closed without merging