[Bug Report] Concurrency problems and low performance when obtaining financial reports
adempiere/adempiere pull request #3839
Opened 2022-05-08 01:40 UTC by e-Evolution

fixed #3759

2022-05-08 06:33 UTC, marcalwestf requested changes
Test with Financial Report
- Name: _Income Statement Current Month_
- Lines: _Income Statement_
- Columns: only one from _Budget YTD_
- Display Line Sources: **YES**

Result:
![imagen](https://user-images.githubusercontent.com/1789408/167284458-9a9d205a-0c0f-4934-bfd8-6c393224f695.png)

Reason:
Method org.compiere.report.FinReport.insertLineSource() creates the SQL wrong:
![imagen](https://user-images.githubusercontent.com/1789408/167284614-b6b1de79-7045-4244-922b-57bd73ee7bcd.png)

After the value of column _LevelNo_, a comma character (**,**)  is missing before the calculation of _Col_0_'s value.

Adding the comma to the SQL, and running it on PGAdmin, yields no error.

When the field _**List Sources**_ is set to **_FALSE_**, then the report is generated correctly:
![imagen](https://user-images.githubusercontent.com/1789408/167284786-8a790019-0280-4dcf-bd6e-ae45242bd755.png)

2022-05-08 08:09 UTC, SusanneCalderon requested changes
It works only without line sources. 
When line sources are included, either in the definition of the report source, or directly, when creating the report, this error occurs.
![imagen](https://user-images.githubusercontent.com/15349639/167287317-38df525b-4142-45af-a010-ca320273897f.png)

Reason: Class FinReport, line 1468
```

     StringBuilder insertLineSource = new StringBuilder("INSERT INTO T_Report "
                    + "(AD_PInstance_ID, PA_ReportLine_ID, Record_ID,Fact_Acct_ID,LevelNo ");

```      
After column _LevelNo,_ no comma is included.

2022-05-08 08:12 UTC, SusanneCalderon commented
@e-Evolution,  it would increase the efficiency or reviewing when you separate name refactoring from code adjustment. Thanks

2022-05-09 20:40 UTC, rcapecce requested changes
Test:

Financial Report: Balance Sheet Current Month
Org: HQ
Definition:
![unknown2](https://user-images.githubusercontent.com/14218144/167492659-ecc325fd-d779-4206-a88a-93d2a3e44778.png)



Result: We found the same message that @marcalwestf and @SusanneCalderon running the financial report

![unknown](https://user-images.githubusercontent.com/14218144/167492296-0afc4e9d-a7aa-4c5c-bacf-92dff5f47ff2.png)

2022-05-09 20:43 UTC, rcapecce requested changes
Test:

Financial Report: Balance Sheet Current Month
Org: HQ
Definition:
![unknown2](https://user-images.githubusercontent.com/14218144/167492659-ecc325fd-d779-4206-a88a-93d2a3e44778.png)



Result: We found the same message that @marcalwestf and @SusanneCalderon running the financial report

![unknown](https://user-images.githubusercontent.com/14218144/167492296-0afc4e9d-a7aa-4c5c-bacf-92dff5f47ff2.png)

The stacktrace

2022-05-09 20:43 UTC, rcapecce commented on base/src/org/compiere/report/FinReport.java
> +            int no = DB.executeUpdateEx(insertLineSource.toString(), trxName);
The stacktrace shows in this insert a sql error

```
org.postgresql.util.PSQLException: ERROR: error de sintaxis en o cerca de ?(?
  Position: 254; State=42601; ErrorCode=0
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
        at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:120)
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
        at sun.reflect.GeneratedMethodAccessor47.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
        at com.sun.proxy.$Proxy4.executeUpdate(Unknown Source)
        at org.compiere.util.DB.executeUpdateEx(DB.java:1098)
        at org.compiere.util.DB.executeUpdateEx(DB.java:1184)
        at org.compiere.util.DB.executeUpdateEx(DB.java:1175)
        at org.compiere.report.FinReport.lambda$insertLineSource$20(FinReport.java:1568)
        at org.compiere.report.FinReport$$Lambda$65/1681504960.run(Unknown Source)
        at org.compiere.util.Trx.run(Trx.java:527)
        at org.compiere.util.Trx.run(Trx.java:495)
        at org.compiere.report.FinReport.insertLineSource(FinReport.java:1465)
        at org.compiere.report.FinReport.insertLineSource(FinReport.java:1289)
        at org.compiere.report.FinReport.lambda$insertLineDetail$16(FinReport.java:1168)
        at org.compiere.report.FinReport$$Lambda$64/656323788.run(Unknown Source)
        at org.compiere.util.Trx.run(Trx.java:527)
        at org.compiere.util.Trx.run(Trx.java:495)
        at org.compiere.report.FinReport.insertLineDetail(FinReport.java:1164)
        at org.compiere.report.FinReport.doIt(FinReport.java:151)
        at org.compiere.process.SvrProcess.process(SvrProcess.java:175)
        at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:128)

```

2022-05-12 19:37 UTC, e-Evolution commented
Hi @marcalwestf Mario, @SusanneCalderon Susanne, @niclopup Nico, @rcapecce Raul, can please test again, I fix the problem with the functionality valid combination, when was integrated from ADAXA contribution not was testing intensively.

2022-05-18 01:39 UTC, marcalwestf approved these changes
- Run the standard Garden World financial reports Balance _Sheet Current Month_, _Income Statement Current Month_ and _Statement of Cash Flows_
- The reports were defined with different values for the following fields: _Report Column Set_, _Cube_, _List Sources_, _List Transactions_
- The reports were run with different values for the following parameters: _Period_, _Cube_, _Details/Source First_
- All reports run without error and displayed a report
- The reports are consistent with the underlying data

Test passed.

**Still, for this pull request to be merged, the tests of data accuracy by** @SusanneCalderon  and @rcapecce **have to be executed**.

2022-05-19 00:42 UTC, SusanneCalderon approved these changes
Tested with a financial report with detail lines successfully. 
![imagen](https://user-images.githubusercontent.com/15349639/169178384-af0d4255-fb57-4ed9-8048-255fce193c4b.png)

2022-05-19 00:58 UTC, merged