fix: #3884 Generate report Null Pointer Exception.
adempiere/adempiere pull request #3887
Opened 2022-05-21 21:49 UTC by EdwinBetanc0urt

#### Steps to reproduce
When executing the Shipment Detail report it stays in a never ending execution.

1. Open the Shipment Detail report.
2. Execute without modifying any parameters.

#### Screenshot or Gif
Before this changes:

https://user-images.githubusercontent.com/20288327/169670003-63321805-8c35-4a65-a9b9-b3ef5dd8aa35.mp4

After this changes:

https://user-images.githubusercontent.com/20288327/169670009-da35b881-d23e-42f9-8232-dab3b5b81827.mp4

#### Additional context

fix: https://github.com/adempiere/adempiere/issues/3884

2022-05-21 22:02 UTC, yamelsenih requested changes
Please change it for fix bug completely

2022-05-21 22:02 UTC, yamelsenih commented on base/src/org/compiere/print/ReportEngine.java
> +				|| (query == null && Optional.ofNullable(pi.getAD_PInstance_ID()).isPresent())
the real bug is here instead: https://github.com/adempiere/adempiere/blob/5d58da08e190e7f4074dc9618f8bb4b32eb15561/base/src/org/compiere/print/ReportEngine.java#L880

You should validate null NPE [here](https://github.com/adempiere/adempiere/blob/5d58da08e190e7f4074dc9618f8bb4b32eb15561/base/src/org/compiere/print/ReportEngine.java#L880)


You can use [this](https://github.com/adempiere/adempiere/blob/5d58da08e190e7f4074dc9618f8bb4b32eb15561/base/src/org/compiere/print/ReportEngine.java#L880) same flow control for it


Some like this: 
```Java
if (query != null) {
  query.addRestriction(whereClause);
  query.setWindowNo(pi.getWindowNo());
}
```

2022-05-21 22:04 UTC, yamelsenih requested changes

2022-05-21 22:04 UTC, yamelsenih commented on base/src/org/compiere/print/ReportEngine.java
> +				|| (query == null && Optional.ofNullable(pi.getAD_PInstance_ID()).isPresent())
Remember remove the additional condition `query == null`

2022-05-22 21:07 UTC, EdwinBetanc0urt commented on base/src/org/compiere/print/ReportEngine.java
> +				|| (query == null && Optional.ofNullable(pi.getAD_PInstance_ID()).isPresent())
Adding the change as you mention, generates a NPE in another place.

![Screenshot_20220522_170127](https://user-images.githubusercontent.com/20288327/169715750-b4bdeb52-43d4-40a3-9d12-dd0a771afdb1.png)

 And even though it has a value (`IsSOTrx='Y'`) in the where clause, the query object was never instantiated and is still null, so it never enters the condition to add the query restriction.

![Screenshot_20220522_170105](https://user-images.githubusercontent.com/20288327/169715743-8788fdc3-c6dc-4bf4-a496-4f6442c5f1e1.png)

2022-05-23 00:16 UTC, EdwinBetanc0urt commented
@yamelsenih I have already applied the suggested changes, for it to work it must remain in the condition:

https://github.com/adempiere/adempiere/pull/3887/files#diff-e6e4fea8b4088210a4e30432da4d3b4ebee36723ece363e4d96572d119ca5c7eR874

`Optional.ofNullable(pi.getAD_PInstance_ID()).isPresent()`

2022-05-23 11:58 UTC, merged