Rename Asset Package
adempiere/adempiere pull request #3943
Opened 2022-07-08 03:26 UTC by yamelsenih

This pull request basically change the package name of Asset to new structure:

Old structure:
```Java
  - org.compiere.model
  - org.compiere.process
```

New structure:
```Java
  - org.compiere.FA.model
  - org.compiere.FA.model.validator
  - org.compiere.FA.process
```

Here some checks:
## Processes
```SQL
SELECT p.Value, p.Name
FROM AD_Process p
WHERE p.ClassName IN('org.compiere.process.AssetDelivery');
```
 
 Value|Name
-- | --
 Asset_Delivery_Selection | Deliver Assets

## Model Validators
```SQL
SELECT mv.Name, mv.Description
FROM AD_ModelValidator mv
WHERE MV.ModelValidationClass IN('org.compiere.FA.model.ModelValidator');
```

Name|Description
--|--
 Model Validator to Fixed Assets | Fixed Assets

## Forms
```SQL
SELECT f.Name, f.Description
FROM AD_Form f
WHERE f.ClassName IN('');
```

Name|Description
--|--

## Final comments

The support legacy api is from here: https://github.com/adempiere/adempiere-asset-support-legacy

2022-07-11 16:39 UTC, marcalwestf commented
This PR is based on the refactoring of fleet package, which is based on the refactoring of WMS.
Thus, both refactoring PRs have to be merged before merging this one; otherwise, they would become obsolete when merging this PR.

2022-07-11 19:43 UTC, marcalwestf commented
@yamelsenih one question: in some classes, I noticed that the import is doing as
`import org.compiere.model.*;`
like in class **org.compiere.FA.model.I_A_Asset**:

![imagen](https://user-images.githubusercontent.com/1789408/178339112-78ecd231-78d7-4e39-add8-b2fd8174a592.png)

This package import can be avoided by explicitly importing each class:
![imagen](https://user-images.githubusercontent.com/1789408/178341154-e6434062-0f8c-484a-9529-08548401cea4.png)

If I remember well, we use to import each class separately.
Consulting the forums (Stack Overflow et. al.) the recommendation is for different reasons to import every class, instead of *.

The classes involved are among others  I_A_Asset, I_A_Asset_Acct, I_A_Asset_Addition, I_A_Asset_Change, I_A_Asset_Class, I_A_Asset_Delivery, I_A_Asset_Disposed, I_A_Asset_Group etc. (actually, all I_* classes, including I_A_Asset* and I_A_Depreciation* and some X classes).

An explicit import has been done for example in X_A_Asset, so it would be symmetrical to do it also in the "I" and "X" classes.

It seems that importing explicitly involves many files. One file is done rapidly, but it adds up in the end.
My question is if it would be possible to do the imports explicitly.

2022-07-11 19:48 UTC, marcalwestf commented
... also the text in the header 

 ```
* For the text or an alternative of this public license, you may reach us    *
 * or via info@adempiere.net                                                  *
 * or https://github.com/adempiere/adempiere/blob/develop/license.html        *
 *****************************************************************************/
```
![imagen](https://user-images.githubusercontent.com/1789408/178345717-12fc599f-43f4-49f3-a145-f8d7b21c6a15.png)

Should eliminate the first "or" in the second line:

 ```
* For the text or an alternative of this public license, you may reach us    *
 * via info@adempiere.net                                                     *
 * or https://github.com/adempiere/adempiere/blob/develop/license.html        *
 *****************************************************************************/
```

2022-07-11 23:21 UTC, marcalwestf requested changes
I get an exception when saving an Asset:
![imagen](https://user-images.githubusercontent.com/1789408/178372012-07ea3ac9-bd88-4649-ab3c-8fe93fd41175.png)

In `DB.executeUpdate()` 
![imagen](https://user-images.githubusercontent.com/1789408/178371614-719e9cf0-4d45-45e7-96b0-65bc501cb182.png)

In  `MAsset.afterSave()`:
![imagen](https://user-images.githubusercontent.com/1789408/178370642-9ca37f69-c849-4ef6-b2b2-7ed260bf96f9.png)

The error can be reproduced in the database:
![imagen](https://user-images.githubusercontent.com/1789408/178372276-d689094d-2a97-40ba-af3c-915b1a871c9b.png)

The only difference is in `MAssetAcct()`:
![imagen](https://user-images.githubusercontent.com/1789408/178374633-9d86f3e1-9418-4c13-9a68-a781dd37e8f7.png)

2022-07-11 23:24 UTC, marcalwestf commented
When executing without the changes of this pull request, Assets can be created on the same database, prior to deactivating `Model Validator to Fixed Assets`.

2022-07-13 16:08 UTC, marcalwestf commented
@yamelsenih please disregard the question of changing the headers. Only the error remains.

I noticed that the headers and imports are generated automatically: 
![imagen](https://user-images.githubusercontent.com/1789408/178778808-10ea12f3-8c7d-4108-8e45-1c94eb548962.png)

It is then useless to change the files manually because they would be changed with the next generation.
The change should be done in `ModelInterfaceGenerator`:
![imagen](https://user-images.githubusercontent.com/1789408/178779808-aa3d39f3-2d37-48a7-82b9-05fb38f20e15.png)

I will create an issue this regarding so new generated class files have a correct header.

2022-07-20 22:00 UTC, yamelsenih commented
> I get an exception when saving an Asset: ![imagen](https://user-images.githubusercontent.com/1789408/178372012-07ea3ac9-bd88-4649-ab3c-8fe93fd41175.png)
> 
> In `DB.executeUpdate()` ![imagen](https://user-images.githubusercontent.com/1789408/178371614-719e9cf0-4d45-45e7-96b0-65bc501cb182.png)
> 
> In `MAsset.afterSave()`: ![imagen](https://user-images.githubusercontent.com/1789408/178370642-9ca37f69-c849-4ef6-b2b2-7ed260bf96f9.png)
> 
> The error can be reproduced in the database: ![imagen](https://user-images.githubusercontent.com/1789408/178372276-d689094d-2a97-40ba-af3c-915b1a871c9b.png)
> 
> The only difference is in `MAssetAcct()`: ![imagen](https://user-images.githubusercontent.com/1789408/178374633-9d86f3e1-9418-4c13-9a68-a781dd37e8f7.png)

Thanks @marcalwestf I will fix it now

2022-07-22 00:05 UTC, yamelsenih commented
Hi I create other pull request here #3952

2022-07-22 00:05 UTC, closed without merging