Rename all packages
adempiere/adempiere pull request #3966
Opened 2022-08-07 02:46 UTC by yamelsenih

Branch: feature/#Src-Change-Packages

Rename base Package

This pull request basically change the package name of all `I_` and `X_` classes to new structure:

Old structure:
```Java
  - it.cnr.imaa.essi.lablib.gui.checkboxtree
  - org.compiere.acct
  - org.eevolution.engine.forecast
  - org.eevolution.exceptions
  - org.eevolution.model
  - org.eevolution.model.impl
  - org.eevolution.model.reasoner
  - org.eevolution.model.wrapper
  - org.eevolution.msg
  - org.eevolution.process
  - org.eevolution.report
  - org.eevolution.tools
  - org.eevolution.tools.worker
```

New structure:
```Java
  - it.cnr.imaa.essi.lablib.gui.checkboxtree
  - org.eevolution.manufacturing.acct
  - org.eevolution.manufacturing.controller
  - org.eevolution.manufacturing.engine.forecast
  - org.eevolution.manufacturing.exceptions
  - org.eevolution.manufacturing.model
  - org.eevolution.manufacturing.model.impl
  - org.eevolution.manufacturing.model.reasoner
  - org.eevolution.manufacturing.model.validator
  - org.eevolution.manufacturing.model.wrapper
  - org.eevolution.manufacturing.msg
  - org.eevolution.manufacturing.process
  - org.eevolution.manufacturing.report
  - org.eevolution.manufacturing.tools
  - org.eevolution.manufacturing.tools.worker
  - org.eevolution.manufacturing.utils
  - org.eevolution.model
```

Here some checks:
## Processes
```SQL
SELECT p.Value, p.Name
FROM AD_Process p
WHERE p.ClassName IN ('org.eevolution.process.CalculateLowLevel', 'org.eevolution.process.CompletePrintOrder', 'org.eevolution.process.ComponentChange', 'org.eevolution.process.CopyCostTypeToCostType', 'org.eevolution.process.CopyFromBOM', 'org.eevolution.process.CopyPriceToStandard', 'org.eevolution.process.CreateCostElement', 'org.eevolution.process.CreateDocType', 'org.eevolution.process.CreatePeriods', 'org.eevolution.process.CreateProductPlanning', 'org.eevolution.process.CRP', 'org.eevolution.process.CRPSummary', 'org.eevolution.process.DistributionRunOrders', 'org.eevolution.process.FixPaymentCashLine', 'org.eevolution.process.ForecastRunCreate', 'org.eevolution.process.FrozenUnFrozenCost', 'org.eevolution.process.GenerateCostDetail', 'org.eevolution.process.GenerateForecast', 'org.eevolution.process.GenerateOrderCost', 'org.eevolution.process.GenerateSalesHistory', 'org.eevolution.process.ImportForecast', 'org.eevolution.process.ImportProductBOM', 'org.eevolution.process.ImportProductPlanning', 'org.eevolution.process.ImportSalesHistory', 'org.eevolution.process.ImportWorkflow', 'org.eevolution.process.MRP', 'org.eevolution.process.MRPApproval', 'org.eevolution.process.MRPSchedule', 'org.eevolution.process.MRPUpdate', 'org.eevolution.process.PP_Product_BOM_Check', 'org.eevolution.process.PrintBOM', 'org.eevolution.process.ProcessInfoHandler', 'org.eevolution.process.ProcessingForecast', 'org.eevolution.process.ProjectGenerateManufacturingOrder', 'org.eevolution.process.RollupBillOfMaterial', 'org.eevolution.process.RollupWorkflow', 'org.eevolution.process.SimulatedPickList', 'org.eevolution.distribution.process.ValidateOrderedAndReservedQuantity');
```
 
 Value|Name
-- | --
 Import_Workflow                        | Import Workflow
 PP_Order GenerateOrderCost             | Generate Manufacturing Order Cost
 Import_ProductBOM                      | Import Product BOM
 PP_Create DocType                      | Create Doc Type to Manufacturing
 PP_Mutiple Components Change           | Mutiple Components Change
 PP_Simulated Pick List                 | Simulated Pick List
 Import_ProductPlanning                 | Import Product Planning and Forecast
 M_DistributionRun Orders               | Distribution Run Orders
 Import_Sales History                   | Import Sales History
 M_Forecast Processing                  | Processing a forecast
 PP_Calculate Forecast                  | PP_Calculate Forecast
 PP_Period Definition  Create Periods   | Create Periods 
 C_SalesHistory_Generate                | Generate Sales History
 M_Forecast Generate Forecast           | Generate Forecast
 Import_Forecast                        | Import Forecast
 M_CostDetail Generate Cost Transaction | Generate Cost Transaction
 MRP_Requisition_Approval               | Requisition Approval
 PP_Calculate Capacity Plan             | Calculate Capacity Plan
 MRP_Manufacturing_Order_Approval       | Manufacturing Order Approval
 MRP_Distribution_Order_Approval        | Distribution Order Approval
 MRP_Schedule                           | Demands and Supplies to schedule
 PP_Product_Planning                    | Create Product Planning
 PP_Calculate Low Level                 | Calculate Low Level
 PP_Create Record MRP                   | Create Record MRP
 PP_Copy Price to Standard Cost         | Copy Price to Standard Cost
 PP_Workflow Cost Roll-Up               | Workflow Cost Roll-Up
 PP_Bill of Material Cost Roll-UP       | Bill of Material & Formula Cost Roll-UP
 PP_Product_BOM CopyFrom                | PP_Product_BOM CopyFrom
 PP_Print & Release Order               | Print & Release Order
 PP_Cost_Element                        | Create Element
 PP_Multi Level BOM & Formula           | Multi Level BOM & Formula Detail
 PP_Cost Frozen/UnFrozen                | Frozen/UnFrozen Cost
 DRP_Calculate Distribution Plan        | Calculate Distribution Plan
 MRP_Regenerative Material Plan         | Regenerative Material Plan
 MRP_Net_Change Material Plan           | Net Change Material Plan
 MRP_Selective Material Plan            | Selective Material Plan
 PP_Copy Cost Type to Cost Type         | Copy Cost Type to other Cost Type
 C_Project_GenerateMO                   | Generate Manufacturing Order from Project
 PP_Product_BOM                         | Verify BOM

## Model Validators
```SQL
SELECT mv.Name, mv.Description
FROM AD_ModelValidator mv
WHERE MV.ModelValidationClass IN('');
```

Name|Description
--|--

## Callouts
```SQL
SELECT t.TableName, c.ColumnName, c.Callout
FROM AD_Table t
INNER JOIN AD_Column c ON(c.AD_Table_ID = t.AD_Table_ID)
WHERE Callout LIKE '%org.eevolution.model.CalloutBOM%'
OR Callout LIKE '%org.eevolution.model.CalloutCostCollector%'
OR Callout LIKE '%org.eevolution.model.CalloutDistributionOrder%'
OR Callout LIKE '%org.eevolution.model.CalloutOrder%'
ORDER BY t.TableName, c.ColumnName;
```
tablename|columnname|callout
--|--|--
 DD_Order           | AD_Org_ID                   | org.eevolution.model.CalloutDistributionOrder.bPartner
 DD_OrderLine       | ConfirmedQty                | org.eevolution.model.CalloutDistributionOrder.qtyConfirmed
 DD_OrderLine       | C_UOM_ID                    | org.eevolution.model.CalloutDistributionOrder.qty
 DD_OrderLine       | M_AttributeSetInstance_ID   | org.eevolution.model.CalloutDistributionOrder.qty
 DD_OrderLine       | M_AttributeSetInstanceTo_ID | org.eevolution.model.CalloutDistributionOrder.qty
 DD_OrderLine       | M_Product_ID                | org.eevolution.model.CalloutDistributionOrder.setLocatorTo
 DD_OrderLine       | QtyEntered                  | org.eevolution.model.CalloutDistributionOrder.qty
 DD_OrderLine       | QtyOrdered                  | org.eevolution.model.CalloutDistributionOrder.qty
 PP_Cost_Collector  | MovementQty                 | org.eevolution.model.CalloutCostCollector.duration
 PP_Cost_Collector  | PP_Order_ID                 | org.eevolution.model.CalloutCostCollector.order
 PP_Cost_Collector  | PP_Order_Node_ID            | org.eevolution.model.CalloutCostCollector.node
 PP_Order           | M_Product_ID                | org.eevolution.model.CalloutOrder.product
 PP_Order           | QtyEntered                  | org.eevolution.model.CalloutOrder.qty;org.eevolution.model.CalloutOrder.qtyBatch
 PP_Order_BOMLine   | QtyEntered                  | org.eevolution.model.CalloutBOM.qtyLine
 PP_Order_BOMLine   | QtyRequired                 | org.eevolution.model.CalloutBOM.qtyLine
 PP_Product_BOM     | M_Product_ID                | org.eevolution.model.CalloutBOM.getdefaults
 PP_Product_BOMLine | M_Product_ID      [...]

2022-08-07 16:37 UTC, marcalwestf commented
@yamelsenih  some questions Yamel:
1. is it intended to build already with gradle?
2. if so, can you deliver a step-by-step instruction to test it?
3. notwithstanding it can be built with gradle or not, I suppose, the compatibility should be 11, instead of 8, shouldn't it?
![imagen](https://user-images.githubusercontent.com/1789408/183301472-af71045d-79ae-4865-9f5c-42187cf7092d.png)

Thanks!

2022-08-07 16:57 UTC, marcalwestf commented
... I see in the Github actions that there is a build with Gradle -BTW exited with an error- so I suppose, it is meant to run with Gradle...

2022-08-07 17:06 UTC, marcalwestf commented
I started a terminal on Eclipse and went to the root of the project and run there 
`gradle build`
this is the result:
![imagen](https://user-images.githubusercontent.com/1789408/183302521-322bcf7b-0314-4f8a-ba74-cd843829da52.png)

My grade version is 6.3:
```
$ gradle -v

Gradle 6.3
------------------------------------------------------------

Build time:   2020-03-24 19:52:07 UTC
Revision:     bacd40b727b0130eeac8855ae3f9fd9a0b207c60

Kotlin:       1.3.70
Groovy:       2.5.10
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          11.0.15 (Azul Systems, Inc. 11.0.15+10-LTS)
OS:           Linux 4.15.0-161-generic i386
```

I will update my grade version and try anew.

2022-08-07 17:34 UTC, yamelsenih commented
> I started a terminal on Eclipse and went to the root of the project and run there `gradle build` this is the result: ![imagen](https://user-images.githubusercontent.com/1789408/183302521-322bcf7b-0314-4f8a-ba74-cd843829da52.png)
> 
> My grade version is 6.3:
> 
> ```
> $ gradle -v
> 
> Gradle 6.3
> ------------------------------------------------------------
> 
> Build time:   2020-03-24 19:52:07 UTC
> Revision:     bacd40b727b0130eeac8855ae3f9fd9a0b207c60
> 
> Kotlin:       1.3.70
> Groovy:       2.5.10
> Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
> JVM:          11.0.15 (Azul Systems, Inc. 11.0.15+10-LTS)
> OS:           Linux 4.15.0-161-generic i386
> ```
> 
> I will update my grade version and try anew.

Hi @marcalwestf 
Here the response:
## Step by Step for build with gradle

**Requirements:**
- Gradle 7.4.1 or later
- Java 8 or later
- Export a eviroment variable named `ADEMIERE_LIBRARY_VERSION`

Export enviroment variable

```Shell
export ADEMIERE_LIBRARY_VERSION="some-version"
```

Build with gradle

```Shell
cd /AdempiereRepo
gradle build
```

2022-08-07 18:44 UTC, yamelsenih commented
Hi @marcalwestf now you can follow the step by step and it should work

Let me know when you are ready

2022-08-08 00:44 UTC, marcalwestf reviewed
- Install gradle version _7.5.1_
- export variable _ADEMIERE_LIBRARY_VERSION_
- variable _JAVA_HOME_ must point to version 8. If it points to version 11, there is an error.
-  run on terminal `gradle build`
Result:
![Selection_289](https://user-images.githubusercontent.com/1789408/183316151-74d6ea70-23c3-4336-bb4d-275ff180b6f9.png)

The IDE (Eclipse) shows no error and finds the class _HikariConfig_
![imagen](https://user-images.githubusercontent.com/1789408/183316277-5b513980-0da9-4752-b27e-9d24305e3882.png)

![imagen](https://user-images.githubusercontent.com/1789408/183318071-011c84aa-31fd-4b6f-a8f0-cf034522bcbf.png)

I suppose the error to be solved is the following:
`class file has wrong version 55.0, should be 52.0`

2022-08-08 23:20 UTC, marcalwestf reviewed
### Test # 1
CRUD at:
- Window , Tab and field
- Table, Column
- Validation
- Organization
- BP - Vendor
- BP - Client
- Product
- Price List
- Price List Vesion
- Price List Schema
- Product Price
- Product PO
- Warehouse
- Locator

- Tax Category
- Product Category
- Product
- Product Info
Result: OK

### Test # 2
Requisition, Requisition Line: CRUD,  prepare, complete
Executing Smart Browser `Browser Requisition to Create PO from Requisition Lines` , the following error is generated:

```
-----------> MTable.getClass: 
No class for table with it entity: PP_MRP [20]

===========> ModelValidationEngine.lambda$18: 
class org.adempiere.core.domains.models.X_PP_MRP cannot be cast to class
org.eevolution.manufacturing.model.MPPMRP 
(org.adempiere.core.domains.models.X_PP_MRP and 
org.eevolution.manufacturing.model.MPPMRP are in unnamed module of loader 'app') [20]
java.lang.ClassCastException: 
class org.adempiere.core.domains.models.X_PP_MRP cannot be cast to class 
org.eevolution.manufacturing.model.MPPMRP 
(org.adempiere.core.domains.models.X_PP_MRP 
and org.eevolution.manufacturing.model.MPPMRP
 are in unnamed module of loader 'app')

at org.eevolution.manufacturing.model.MPPMRP.M_RequisitionLine(MPPMRP.java:984)
```

![imagen](https://user-images.githubusercontent.com/1789408/183529840-595475cb-3910-4f00-bcc7-c9734f6e2704.png)

2022-08-08 23:46 UTC, marcalwestf commented
@yamelsenih  Yamel, same happens when process `Create PO from Requisition` is called:
![imagen](https://user-images.githubusercontent.com/1789408/183533141-17ba860e-b536-4510-9acf-e971c68bc5ee.png)

2022-08-08 23:57 UTC, marcalwestf commented
...and when saving a Purchase Order:
![imagen](https://user-images.githubusercontent.com/1789408/183534220-6f089dd3-811d-485a-a840-00bca8eb13f7.png)

2022-08-09 00:10 UTC, marcalwestf requested changes
The following error is also generated when processing Purchase Orders and Sales Orders.
I will pause the test until this is corrected because many objects will be involved:
```
===========> ModelValidationEngine.lambda$18: class org.adempiere.core.domains.models.X_PP_MRP cannot be cast to class org.eevolution.manufacturing.model.MPPMRP (org.adempiere.core.domains.models.X_PP_MRP and org.eevolution.manufacturing.model.MPPMRP are in unnamed module of loader 'app') [569]
java.lang.ClassCastException: class org.adempiere.core.domains.models.X_PP_MRP cannot be cast to class org.eevolution.manufacturing.model.MPPMRP (org.adempiere.core.domains.models.X_PP_MRP and org.eevolution.manufacturing.model.MPPMRP are in unnamed module of loader 'app')
	at org.eevolution.manufacturing.model.MPPMRP.C_Order(MPPMRP.java:737)
	at org.eevolution.manufacturing.model.validator.Libero.modelChange(Libero.java:168)
```

2022-08-09 00:11 UTC, marcalwestf commented
..also the execution of 
`gradle build `
delivers error

2022-08-09 01:37 UTC, marcalwestf reviewed
### Test # 3
Load and apply XML file `09850_Rename_Manufacturing_Package.xml` (I hdn't found it before)

I could then do the following without problems:
- Requisition, Requisition Line: CRUD, prepare, complete
- Smart Browser Browser Requisition to Create PO from Requisition Lines
- Purchase Order: CRUD, prepare, complete
- Material Receipt: CRUD, prepare, complete
- Purchase Invoice: CRUD, prepare, complete
- Sales Order: CRUD, prepare, complete
- Material Shipment: CRUD, prepare, complete
- Sales  Invoice: CRUD, prepare, complete
- RMA: CRUD, prepare, complete
- Payment: CRUD, prepare, complete
- Report: Payment Details
- Report: Payment Selection
- Create Dunning Run
- Payment Allocation
- Report: Allocation
- Print Format
- Report: Bank Statement Report
- Bank Statement: CRUD, prepare, complete

The error I got in tests before came because this XML file was not applied.

Still to do: Production and Manufacturing tests.

2022-08-09 15:59 UTC, yamelsenih commented
> 09850_Rename_Manufacturing_Package

@marcalwestf thanks...

Now you can validate other?

Exists other error?

2022-08-09 21:06 UTC, marcalwestf reviewed
### Test # 4
- Material Movement -> OK
- BOM -> OK
- BOM Component -> OK
- Verify BOM -> OK
- BOM & Formula Info -> OK
- Production CRUD, prepare, complete -> **ERROR**
```
org.postgresql.util.PSQLException: ERROR: column "value" does not exist
Position: 673, SQL=SELECT Updated,Created,IsActive,(SELECT o.C_BPartner_ID FROM C_Order o INNER JOIN C_OrderLine ol ON (ol.C_Order_ID=o.C_Order_ID) WHERE ol.C_OrderLine_ID=M_Production.C_OrderLine_ID) AS C_BPartner_ID,User3_ID,User4_ID,MovementDate,DocumentNo,ProductionQty,M_Locator_ID,Description,IsWIP,M_ProductionBatch_ID,MustBeStocked,IsComplete,Name,IsCreated,DatePromised,C_OrderLine_ID,AD_Org_ID,AD_Client_ID,C_DocType_ID,UpdatedBy,M_Production_ID,CreatedBy,User1_ID,C_Activity_ID,C_Campaign_ID,M_Product_ID,AD_OrgTrx_ID,C_Project_ID,User2_ID,UUID,PP_Product_BOM_ID,Posted,Processing,Processed,DocStatus,DocAction,ProcessedOn,Reversal_ID FROM M_Production WHERE (M_Product_ID=? AND Value=?) AND IsActive=? AND AD_Client_ID=?
```
![imagen](https://user-images.githubusercontent.com/1789408/183760557-f0628c3f-4771-464a-bb10-a570d3b05f3b.png)

The corresponding Query expects a column named `value`,  that doesn't exist in table `MProduction`:
![imagen](https://user-images.githubusercontent.com/1789408/183761386-f4910cd8-b497-4210-aa67-6d35ca6d63f5.png)

2022-08-09 21:12 UTC, marcalwestf commented
Gradle error still exists: I followed the instructions and there is an error:
```
$ export PATH=/opt/gradle/gradle-7.5.1/bin:$PATH
$ export ADEMIERE_LIBRARY_VERSION="some-version"
$ JAVA_HOME=/usr/lib/jvm/java-8-oracle
$ gradle build
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :base:compileJava
/home/westfalia/Adempiere/westfaliaRepository_2022-06/adempiere_erpcya/base/src/org/compiere/db/DB_Oracle.java:38: error: cannot access com.zaxxer.hikari.HikariConfig
import com.zaxxer.hikari.HikariConfig;
                        ^
  bad class file: /home/westfalia/.gradle/caches/modules-2/files-2.1/com.zaxxer/HikariCP/5.0.1/a74c7f0a37046846e88d54f7cb6ea6d565c65f9c/HikariCP-5.0.1.jar(com/zaxxer/hikari/HikariConfig.class)
    class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.

> Task :base:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':base:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 33s
5 actionable tasks: 5 executed
westfalia@asus-kubuntu1:/home/westfalia/Adempiere/westfaliaRepository_2022-06/adempiere_erpcya$ 




```

2022-08-10 03:13 UTC, marcalwestf reviewed
### Test # 5: Payroll
- Payroll employee setup -> OK
- Department -> OK
- Payroll table, table version, table line -> OK
- Category -> OK
- Concept -> OK
- Concept type amount -> OK
- Concept for employee -> OK
- Concept type Rule -> OK
- Payroll definition -> OK
- Year, period -> OK
- Year, Create Periods -> OK
- Payroll Process, prepare -> OK
- Result: the rule was calculated correctly -> OK
- Payroll Movement Report -> OK
- Create Report Definition -> OK
- Browser Global Payroll Concept -> OK
- Browser History Payroll Movement -> OK

**Result: Payroll OK**

2022-08-10 03:32 UTC, marcalwestf commented
### Test # 6: Jasper Reports
- Load and apply XML file as described in https://github.com/adempiere/adempiere/pull/3929
![imagen](https://user-images.githubusercontent.com/1789408/183807093-41d70929-86a9-4237-833f-66e03c12aa00.png)

- Run Role Access Update
- Run  Jasper Report Test
![imagen](https://user-images.githubusercontent.com/1789408/183806543-391ad950-950c-47fc-a8f9-a81989b8b645.png)

Error is produced: `java.lang.ClassNotFoundException: org.compiere.report.ReportStarter` although the class is found in the IDE
![imagen](https://user-images.githubusercontent.com/1789408/183806819-cb517f1b-e9db-41f7-8950-566603d6be63.png)

2022-08-10 14:10 UTC, marcalwestf reviewed
### Test # 7: Misc Tests
- Sales Region -> OK
- Commission Type -> OK
- Commission group -> OK
- Commission Definition -> OK
- Commission Run: CRUD, prepare, complete -> OK
- Process Create Invoice from Commission -> OK
- Report Commission Run (Summary) -> OK
- Report Commission Run (Detail) -> OK
- Report: Shipment Details -> OK
- `All Sales Reports` -> OK
- Print Format CRUD -> OK
- Print Paper CRUD -> OK
-  Process CRUD -> OK

**No errors**

2022-08-10 14:10 UTC, marcalwestf commented
... now I am going to test Libero....

2022-08-10 14:13 UTC, yamelsenih commented
> * Install gradle version _7.5.1_ **and** point variable PATH to this version
> * export variable _ADEMIERE_LIBRARY_VERSION_
> * variable _JAVA_HOME_ must point to version 8. If it points to version 11, there is an error.
> * run on terminal `gradle build`
>   Result:
>   ![Selection_289](https://user-images.githubusercontent.com/1789408/183316151-74d6ea70-23c3-4336-bb4d-275ff180b6f9.png)
> 
> The IDE (Eclipse) shows no error and finds the class _HikariConfig_ ![imagen](https://user-images.githubusercontent.com/1789408/183316277-5b513980-0da9-4752-b27e-9d24305e3882.png)
> 
> ![imagen](https://user-images.githubusercontent.com/1789408/183318071-011c84aa-31fd-4b6f-a8f0-cf034522bcbf.png)
> 
> I suppose the error to be solved is the following: `class file has wrong version 55.0, should be 52.0`

Hi @marcalwestf have you a fresh repo? Try downloading a standalone repo and run Gradle. Is very strange that the Gradle building is worked on GitHub action but not for you.

Let me know any results or questions

2022-08-10 18:04 UTC, marcalwestf reviewed
### Test # 8: Libero
- Resource Type -> OK
- Manufacturing Resource -> OK
- MRP Info -> OK
- Product Data Planning -> OK
- BOM Copy Lines From -> OK
- Report Multilevel BOM & Formula Detail -> OK
- Report Simulated Pick List -> OK
- Forecast Definition -> OK
- Process Create Periods -> OK
- Forecast Simulation -> OK
- Process Calculate Forecast -> OK
- Forecast Simulation Result -> OK
- Calculate Low Level -> OK
- Create Record MRP -> OK
- Regenerative Material Plan -> OK
- Net Change Material Plan -> OK
- Selective Material Plan -> OK
- MRP Action Messages -> OK
- Report MRP Details -> OK
- Browse Purchase Order -> OK
- Create Manufacturing Order -> Generates error when trying to get the `RoutingService` class.
![imagen](https://user-images.githubusercontent.com/1789408/183984642-b41d2c13-a19e-4b07-8e3d-980cf54c8b99.png)

![imagen](https://user-images.githubusercontent.com/1789408/183984348-d1231cc5-0bf9-430b-82fd-ece76d2a15fe.png)

2022-08-10 18:31 UTC, e-Evolution requested changes
@yamelsenih I found next errors :

    [javac] /Users/e-Evolution/Develop/ADempiere/394IO/base/src/org/eevolution/process/EnableNativeSequenceForDocumentNo.java:62: error: cannot find symbol
    [javac] 			List<MSequence> documentSequences = new Query(getCtx(),X_AD_Sequence.Table_Name, whereClause, get_TrxName()).list();
    [javac] 			                                                       ^
    [javac]   symbol:   variable X_AD_Sequence
    [javac]   location: class EnableNativeSequenceForDocumentNo
    [javac] Note: Some input files additionally use or override a deprecated API.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 1 error
    [javac] 100 warnings

BUILD FAILED
/Users/e-Evolution/Develop/ADempiere/394IO/utils_dev/build.xml:21: The following error occurred while executing this line:
/Users/e-Evolution/Develop/ADempiere/394IO/base/build.xml:69: Compile failed; see the compiler error output for details.

Here other error when execute : 

![image](https://user-images.githubusercontent.com/786968/183989834-ff2acae2-52ee-4911-b704-2d412141b0e9.png)


-----------> Msg.getMsg: NOT found: QuickEntry [43]
===========> CRP.process: java.lang.ClassNotFoundException: org.eevolution.model.impl.DefaultRoutingServiceImpl [81]
java.lang.ClassNotFoundException: org.eevolution.model.impl.DefaultRoutingServiceImpl
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.eevolution.model.RoutingServiceFactory.getRoutingService(RoutingServiceFactory.java:62)
	at org.eevolution.manufacturing.process.CRP.doIt(CRP.java:91)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:176)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:129)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:171)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:116)
	at org.compiere.apps.ProcessCtl.startProcess(ProcessCtl.java:610)
	at org.compiere.apps.ProcessCtl.run(ProcessCtl.java:360)
	at org.adempiere.webui.apps.ProcessPanel.runProcess(ProcessPanel.java:688)
	at org.adempiere.webui.apps.ProcessDialog.runProcess(ProcessDialog.java:155)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.zkoss.zk.ui.impl.EventProcessor.process0(EventProcessor.java:209)
	at org.zkoss.zk.ui.impl.EventProcessor.process(EventProcessor.java:141)
	at org.zkoss.zk.ui.impl.EventProcessingThreadImpl.process0(EventProcessingThreadImpl.java:519)
	at org.zkoss.zk.ui.impl.EventProcessingThreadImpl.run(EventProcessingThreadImpl.java:446)

===========> CRP.process: java.lang.ClassNotFoundException: org.eevolution.model.impl.DefaultRoutingServiceImpl [81]
java.lang.ClassNotFoundException: org.eevolution.model.impl.DefaultRoutingServiceImpl
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.eevolution.model.RoutingServiceFactory.getRoutingService(RoutingServiceFactory.java:62)
	at org.eevolution.manufacturing.process.CRP.doIt(CRP.java:91)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:176)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:129)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:171)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:116)
	at org.compiere.apps.ProcessCtl.startProcess(ProcessCtl.java:610)
	at org.compiere.apps.ProcessCtl.run(ProcessCtl.java:360)
	at org.adempiere.webui.apps.ProcessPanel.runProcess(ProcessPanel.java:688)
	at org.adempiere.webui.apps.ProcessDialog.runProcess(ProcessDialog.java:155)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.zkoss.zk.ui.impl.EventProcessor.process0(EventProcessor.java:209)
	at org.zkoss.zk.ui.impl.EventProcessor.process(EventProcessor.java:141)
	at org.zkoss.zk.ui.impl.EventProcessingThreadImpl.process0(EventProcessingThreadImpl.java:519)
	at org.zkoss.zk.ui.impl.EventProcessingThreadImpl.run(EventProcessingThreadImpl.java:446)

2022-08-10 18:35 UTC, e-Evolution commented
@yamelsenih other error when try save a Manufacturing Order

![image](https://user-images.githubusercontent.com/786968/183990432-1b02d5bc-fd50-40b7-bb91-91cddb54c2ed.png)

2022-08-10 18:37 UTC, e-Evolution commented
Other more when try complete the Manufacturing Order :

-----------> Msg.translate: NOT found: Altert UOM [43]
-----------> Msg.translate: NOT found: Altert UOM [43]
===========> DocumentEngine.getDoc: Doc Class invalid: org.compiere.acct.Doc_PPOrder (java.lang.ClassNotFoundException: org.compiere.acct.Doc_PPOrder) [81]
===========> DocumentEngine.getDoc: Doc Class invalid: org.compiere.acct.Doc_PPOrder (java.lang.ClassNotFoundException: org.compiere.acct.Doc_PPOrder) [81]
===========> DocumentEngine.getDoc: SELECT * FROM PP_Order WHERE PP_Order_ID=? AND Processed='Y' [81]
UserError: Doc Class invalid: org.compiere.acct.Doc_PPOrder (java.lang.ClassNotFoundException: org.compiere.acct.Doc_PPOrder)
	at org.compiere.process.DocumentEngine.getDoc(DocumentEngine.java:1602)
	at org.compiere.process.DocumentEngine.getDoc(DocumentEngine.java:1553)
	at org.compiere.process.DocumentEngine.postImmediate(DocumentEngine.java:1470)
	at org.compiere.process.DocumentEngine.postIt(DocumentEngine.java:576)
	at org.compiere.process.DocumentEngine.postTheDocAndAnyPostProcessDocs(DocumentEngine.java:366)
	at org.compiere.process.DocumentEngine.prepareThenCompleteIt(DocumentEngine.java:353)
	at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:318)
	at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:289)
	at org.eevolution.manufacturing.model.MPPOrder.processIt(MPPOrder.java:533)
	at org.compiere.wf.MWFActivity.performWork(MWFActivity.java:861)
	at org.compiere.wf.MWFActivity.run(MWFActivity.java:781)
	at org.compiere.wf.MWFProcess.startNext(MWFProcess.java:341)
	at org.compiere.wf.MWFProcess.checkActivities(MWFProcess.java:256)
	at org.compiere.wf.MWFActivity.setWFState(MWFActivity.java:284)
	at org.compiere.wf.MWFActivity.run(MWFActivity.java:784)
	at org.compiere.wf.MWFProcess.startNext(MWFProcess.java:341)
	at org.compiere.wf.MWFProcess.checkActivities(MWFProcess.java:256)
	at org.compiere.wf.MWFActivity.setWFState(MWFActivity.java:284)
	at org.compiere.wf.MWFActivity.run(MWFActivity.java:784)
	at org.compiere.wf.MWFProcess.startWork(MWFProcess.java:471)
	at org.compiere.wf.MWorkflow.start(MWorkflow.java:731)
	at org.compiere.wf.MWorkflow.startWait(MWorkflow.java:787)

===========> DocumentEngine.getDoc: SELECT * FROM PP_Order WHERE PP_Order_ID=? AND Processed='Y' [81]
UserError: Doc Class invalid: org.compiere.acct.Doc_PPOrder (java.lang.ClassNotFoundException: org.compiere.acct.Doc_PPOrder)
	at org.compiere.process.DocumentEngine.getDoc(DocumentEngine.java:1602)
	at org.compiere.process.DocumentEngine.getDoc(DocumentEngine.java:1553)
	at org.compiere.process.DocumentEngine.postImmediate(DocumentEngine.java:1470)
	at org.compiere.process.DocumentEngine.postIt(DocumentEngine.java:576)
	at org.compiere.process.DocumentEngine.postTheDocAndAnyPostProcessDocs(DocumentEngine.java:366)
	at org.compiere.process.DocumentEngine.prepareThenCompleteIt(DocumentEngine.java:353)
	at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:318)
	at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:289)
	at org.eevolution.manufacturing.model.MPPOrder.processIt(MPPOrder.java:533)
	at org.compiere.wf.MWFActivity.performWork(MWFActivity.java:861)
	at org.compiere.wf.MWFActivity.run(MWFActivity.java:781)
	at org.compiere.wf.MWFProcess.startNext(MWFProcess.java:341)
	at org.compiere.wf.MWFProcess.checkActivities(MWFProcess.java:256)
	at org.compiere.wf.MWFActivity.setWFState(MWFActivity.java:284)
	at org.compiere.wf.MWFActivity.run(MWFActivity.java:784)
	at org.compiere.wf.MWFProcess.startNext(MWFProcess.java:341)
	at org.compiere.wf.MWFProcess.checkActivities(MWFProcess.java:256)
	at org.compiere.wf.MWFActivity.setWFState(MWFActivity.java:284)
	at org.compiere.wf.MWFActivity.run(MWFActivity.java:784)
	at org.compiere.wf.MWFProcess.startWork(MWFProcess.java:471)
	at org.compiere.wf.MWorkflow.start(MWorkflow.java:731)
	at org.compiere.wf.MWorkflow.startWait(MWorkflow.java:787)

2022-08-10 18:48 UTC, e-Evolution commented
@yamelsenih , here other error when report Receipt and Issue : 

![image](https://user-images.githubusercontent.com/786968/183993141-e7b3112b-2c04-49ad-a728-62d87b66f367.png)


-----------> Msg.translate: NOT found: Altert UOM [43]
-----------> MSequence.getDocumentNo: (DocType)- no record found - MDocType[50013-Manufacturing Cost Collector,DocNoSequence_ID=53272] [81]
-----------> MSequence.getDocumentNo: (DocType)- no record found - MDocType[50013-Manufacturing Cost Collector,DocNoSequence_ID=53272] [81]
===========> DocumentEngine.getDoc: Doc Class invalid: org.compiere.acct.Doc_PPCostCollector (java.lang.ClassNotFoundException: org.compiere.acct.Doc_PPCostCollector) [81]
===========> DocumentEngine.getDoc: Doc Class invalid: org.compiere.acct.Doc_PPCostCollector (java.lang.ClassNotFoundException: org.compiere.acct.Doc_PPCostCollector) [81]
===========> DocumentEngine.getDoc: SELECT * FROM PP_Cost_Collector WHERE PP_Cost_Collector_ID=? AND Processed='Y' [81]
UserError: Doc Class invalid: org.compiere.acct.Doc_PPCostCollector (java.lang.ClassNotFoundException: org.compiere.acct.Doc_PPCostCollector)
	at org.compiere.process.DocumentEngine.getDoc(DocumentEngine.java:1602)
	at org.compiere.process.DocumentEngine.getDoc(DocumentEngine.java:1553)
	at org.compiere.process.DocumentEngine.postImmediate(DocumentEngine.java:1470)
	at org.compiere.process.DocumentEngine.postIt(DocumentEngine.java:576)
	at org.compiere.process.DocumentEngine.postTheDocAndAnyPostProcessDocs(DocumentEngine.java:366)
	at org.compiere.process.DocumentEngine.prepareThenCompleteIt(DocumentEngine.java:353)
	at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:318)
	at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:289)
	at org.eevolution.manufacturing.model.MPPCostCollector.processIt(MPPCostCollector.java:293)
	at org.eevolution.manufacturing.model.MPPCostCollector.createCollector(MPPCostCollector.java:177)
	at org.eevolution.manufacturing.model.MPPOrder.createIssue(MPPOrder.java:1266)
	at org.eevolution.form.OrderReceiptIssue.createIssue(OrderReceiptIssue.java:323)
	at org.eevolution.form.WOrderReceiptIssue$1.run(WOrderReceiptIssue.java:924)
	at org.compiere.util.Trx.run(Trx.java:529)
	at org.compiere.util.Trx.run(Trx.java:497)

===========> DocumentEngine.getDoc: SELECT * FROM PP_Cost_Collector WHERE PP_Cost_Collector_ID=? AND Processed='Y' [81]
UserError: Doc Class invalid: org.compiere.acct.Doc_PPCostCollector (java.lang.ClassNotFoundException: org.compiere.acct.Doc_PPCostCollector)
	at org.compiere.process.DocumentEngine.getDoc(DocumentEngine.java:1602)
	at org.compiere.process.DocumentEngine.getDoc(DocumentEngine.java:1553)
	at org.compiere.process.DocumentEngine.postImmediate(DocumentEngine.java:1470)
	at org.compiere.process.DocumentEngine.postIt(DocumentEngine.java:576)
	at org.compiere.process.DocumentEngine.postTheDocAndAnyPostProcessDocs(DocumentEngine.java:366)
	at org.compiere.process.DocumentEngine.prepareThenCompleteIt(DocumentEngine.java:353)
	at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:318)
	at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:289)
	at org.eevolution.manufacturing.model.MPPCostCollector.processIt(MPPCostCollector.java:293)
	at org.eevolution.manufacturing.model.MPPCostCollector.createCollector(MPPCostCollector.java:177)
	at org.eevolution.manufacturing.model.MPPOrder.createIssue(MPPOrder.java:1266)
	at org.eevolution.form.OrderReceiptIssue.createIssue(OrderReceiptIssue.java:323)
	at org.eevolution.form.WOrderReceiptIssue$1.run(WOrderReceiptIssue.java:924)
	at org.compiere.util.Trx.run(Trx.java:529)
	at org.compiere.util.Trx.run(Trx.java:497)

-----------> MSequence.getDocumentNo: (DocType)- no record found - MDocType[50013-Manufacturing Cost Collector,DocNoSequence_ID=53272] [81]
-----------> MSequence.getDocumentNo: (DocType)- no record found - MDocType[50013-Manufacturing Cost Collector,DocNoSequence_ID=53272] [81]
===========> DocumentEngine.getDoc: Doc Class invalid: org.compiere.acct.Doc_PPCostCollector (java.lang.ClassNotFoundException: org.compiere.acct.Doc_PPCostCollector) [81]
===========> DocumentEngine.getDoc: Doc Class invalid: org.compiere.acct.Doc_PPCostCollector (java.lang.ClassNotFoundException: org.compiere.acct.Doc_PPCostCollector) [81]
===========> DocumentEngine.getDoc: SELECT * FROM PP_Cost_Collector WHERE PP_Cost_Collector_ID=? AND Processed='Y' [81]
UserError: Doc Class invalid: org.compiere.acct.Doc_PPCostCollector (java.lang.ClassNotFoundException: org.compiere.acct.Doc_PPCostCollector)
	at org.compiere.process.DocumentEngine.getDoc(DocumentEngine.java:1602)
	at org.compiere.process.DocumentEngine.getDoc(DocumentEngine.java:1553)
	at org.compiere.process.DocumentEngine.postImmediate(DocumentEngine.java:1470)
	at org.compiere.process.DocumentEngine.postIt(DocumentEngine.java:576)
	at org.compiere.process.DocumentEngine.postTheDocAndAnyPostProcessDocs(DocumentEngine.java:366)
	at org.compiere.process.DocumentEngine.prepareThenCompleteIt(DocumentEngine.java:353)
	at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:318)
	at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:289)
	at org.eevolution.manufacturing.model.MPPCostCollector.processIt(MPPCostCollector.java:293)
	at org.eevolution.manufacturing.model.MPPCostCollector.createCollector(MPPCostCollector.java:177)
	at org.eevolution.manufacturing.model.MPPOrder.createIssue(MPPOrder.java:1266)
	at org.eevolution.form.OrderReceiptIssue.createIssue(OrderReceiptIssue.java:323)
	at org.eevolution.form.WOrderReceiptIssue$1.run(WOrderReceiptIssue.java:924)
	at org.compiere.util.Trx.run(Trx.java:529)
	at org.compiere.util.Trx.run(Trx.java:497)

===========> DocumentEngine.getDoc: SELECT * FROM PP_Cost_Collector WHERE PP_Cost_Collector_ID=? AND Processed='Y' [81]
UserError: Doc Class invalid: org.compiere.acct.Doc_PPCostCollector (java.lang.ClassNotFoundException: org.compiere.acct.Doc_PPCostCollector)
	at org.compiere.process.DocumentEngine.getDoc(DocumentEngine.java:1602)
	at org.compiere.process.DocumentEngine.getDoc(DocumentEngine.java:1553)
	at org.compiere.process.DocumentEngine.postImmediate(DocumentEngine.java:1470)
	at org.compiere.process.DocumentEngine.postIt(DocumentEngine.java:576)
	at org.compiere.process.DocumentEngine.postTheDocAndAnyPostProcessDocs(DocumentEngine.java:366)
	at org.compiere.process.DocumentEngine.prepareThenCompleteIt(DocumentEngine.java:353)
	at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:318)
	at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:289)
	at org.eevolution.manufacturing.model.MPPCostCollector.processIt(MPPCostCollector.java:293)
	at org.eevolution.manufacturing.model.MPPCostCollector.createCollector(MPPCostCollector.java:177)
	at org.eevolution.manufacturing.model.MPPOrder.createIssue(MPPOrder.java:1266)
	at org.eevolution.form.OrderReceiptIssue.createIssue(OrderReceiptIssue.java:323)
	at org.eevolution.form.WOrderReceiptIssue$1.run(WOrderReceiptIssue.java:924)
	at org.compiere.util.Trx.run(Trx.java:529)
	at org.compiere.util.Trx.run(Trx.java:497)

-----------> MSequence.getDocumentNo: (DocType)- no record found - MDocType[50013-Manufacturing Cost Collector,DocNoSequence_ID=53272] [81]
-----------> MSequence.getDocumentNo: (DocType)- no record found - MDocType[50013-Manufacturing Cost Collector,DocNoSequence_ID=53272] [81]
===========> DocumentEngine.getDoc: Doc Class invalid: org.compiere.acct.Doc_PPCostCollector (java.lang.ClassNotFoundException: org.compiere.acct.Doc_PPCostCollector) [81]
===========> DocumentEngine.getDoc: Doc Class invalid: org.compiere.acct.Doc_PPCostCollector (java.lang.ClassNotFoundException: org.compiere.acct.Doc_PPCostCollector) [81]
===========> DocumentEngine.getDoc: SELECT * FROM PP_Cost_Collector WHERE PP_Cost_Collector_ID=? AND Processed='Y' [81]
UserError: Doc Class invalid: org.compiere.acct.Doc_PPCostCollector (java.lang.ClassNotFoundException: org.compiere. [...]

2022-08-10 18:51 UTC, e-Evolution commented
Other error when try report Activity Control : 

![image](https://user-images.githubusercontent.com/786968/183993380-40a3dc8c-bba5-4863-ae58-5900ddd0cbc0.png)


-----------> Msg.getMsg: NOT found: QuickEntry [43]
-----------> Msg.getMsg: NOT found: QuickEntry [43]
===========> CalloutCostCollector.start: start: duration [81]
org.adempiere.exceptions.AdempiereException: java.lang.ClassNotFoundException: org.eevolution.model.impl.DefaultRoutingServiceImpl
	at org.eevolution.model.RoutingServiceFactory.getRoutingService(RoutingServiceFactory.java:68)
	at org.eevolution.model.RoutingServiceFactory.getRoutingService(RoutingServiceFactory.java:75)
	at org.eevolution.manufacturing.controller.CalloutCostCollector.duration(CalloutCostCollector.java:77)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.compiere.model.CalloutEngine.start(CalloutEngine.java:109)
	at org.compiere.model.GridTab.processCallout(GridTab.java:2719)
	at org.compiere.model.GridTab.processFieldChange(GridTab.java:2533)
	at org.adempiere.webui.panel.ADTabPanel.dataStatusChanged(ADTabPanel.java:1128)
	at org.compiere.model.GridTab.fireDataStatusChanged(GridTab.java:2135)
	at org.compiere.model.GridTab.dataStatusChanged(GridTab.java:2108)
	at org.compiere.model.GridTable.fireDataStatusChanged(GridTable.java:3288)
	at org.compiere.model.GridTable.setValueAt(GridTable.java:1290)
	at org.compiere.model.GridTab.setValue(GridTab.java:2499)
	at org.compiere.model.GridTab.setValue(GridTab.java:2479)
caused by: java.lang.ClassNotFoundException: org.eevolution.model.impl.DefaultRoutingServiceImpl
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.eevolution.model.RoutingServiceFactory.getRoutingService(RoutingServiceFactory.java:62)
	at org.eevolution.model.RoutingServiceFactory.getRoutingService(RoutingServiceFactory.java:75)
	at org.eevolution.manufacturing.controller.CalloutCostCollector.duration(CalloutCostCollector.java:77)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.compiere.model.CalloutEngine.start(CalloutEngine.java:109)
	at org.compiere.model.GridTab.processCallout(GridTab.java:2719)
	at org.compiere.model.GridTab.processFieldChange(GridTab.java:2533)
	at org.adempiere.webui.panel.ADTabPanel.dataStatusChanged(ADTabPanel.java:1128)
	at org.compiere.model.GridTab.fireDataStatusChanged(GridTab.java:2135)
	at org.compiere.model.GridTab.dataStatusChanged(GridTab.java:2108)
	at org.compiere.model.GridTable.fireDataStatusChanged(GridTable.java:3288)
	at org.compiere.model.GridTable.setValueAt(GridTable.java:1290)
	at org.compiere.model.GridTab.setValue(GridTab.java:2499)
	at org.compiere.model.GridTab.setValue(GridTab.java:2479)

===========> CalloutCostCollector.start: start: duration [81]
org.adempiere.exceptions.AdempiereException: java.lang.ClassNotFoundException: org.eevolution.model.impl.DefaultRoutingServiceImpl
	at org.eevolution.model.RoutingServiceFactory.getRoutingService(RoutingServiceFactory.java:68)
	at org.eevolution.model.RoutingServiceFactory.getRoutingService(RoutingServiceFactory.java:75)
	at org.eevolution.manufacturing.controller.CalloutCostCollector.duration(CalloutCostCollector.java:77)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.compiere.model.CalloutEngine.start(CalloutEngine.java:109)
	at org.compiere.model.GridTab.processCallout(GridTab.java:2719)
	at org.compiere.model.GridTab.processFieldChange(GridTab.java:2533)
	at org.adempiere.webui.panel.ADTabPanel.dataStatusChanged(ADTabPanel.java:1128)
	at org.compiere.model.GridTab.fireDataStatusChanged(GridTab.java:2135)
	at org.compiere.model.GridTab.dataStatusChanged(GridTab.java:2108)
	at org.compiere.model.GridTable.fireDataStatusChanged(GridTable.java:3288)
	at org.compiere.model.GridTable.setValueAt(GridTable.java:1290)
	at org.compiere.model.GridTab.setValue(GridTab.java:2499)
	at org.compiere.model.GridTab.setValue(GridTab.java:2479)
caused by: java.lang.ClassNotFoundException: org.eevolution.model.impl.DefaultRoutingServiceImpl
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.eevolution.model.RoutingServiceFactory.getRoutingService(RoutingServiceFactory.java:62)
	at org.eevolution.model.RoutingServiceFactory.getRoutingService(RoutingServiceFactory.java:75)
	at org.eevolution.manufacturing.controller.CalloutCostCollector.duration(CalloutCostCollector.java:77)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.compiere.model.CalloutEngine.start(CalloutEngine.java:109)
	at org.compiere.model.GridTab.processCallout(GridTab.java:2719)
	at org.compiere.model.GridTab.processFieldChange(GridTab.java:2533)
	at org.adempiere.webui.panel.ADTabPanel.dataStatusChanged(ADTabPanel.java:1128)
	at org.compiere.model.GridTab.fireDataStatusChanged(GridTab.java:2135)
	at org.compiere.model.GridTab.dataStatusChanged(GridTab.java:2108)
	at org.compiere.model.GridTable.fireDataStatusChanged(GridTable.java:3288)
	at org.compiere.model.GridTable.setValueAt(GridTable.java:1290)
	at org.compiere.model.GridTab.setValue(GridTab.java:2499)
	at org.compiere.model.GridTab.setValue(GridTab.java:2479)

2022-08-10 19:14 UTC, e-Evolution commented
Other errors :

![image](https://user-images.githubusercontent.com/786968/183998265-905935c2-1e8f-458b-a2ce-b2e9689def71.png)

===========> CreateDocType.createDocType: Sequence NOT created - Distribution Order [43]
===========> CreateDocType.createDocType: Sequence NOT created - Distribution Order [43]
===========> RollupWorkflow.process: java.lang.ClassNotFoundException: org.eevolution.model.impl.DefaultRoutingServiceImpl [81]
java.lang.ClassNotFoundException: org.eevolution.model.impl.DefaultRoutingServiceImpl
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.eevolution.model.RoutingServiceFactory.getRoutingService(RoutingServiceFactory.java:62)
	at org.eevolution.manufacturing.process.RollupWorkflow.doIt(RollupWorkflow.java:74)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:176)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:129)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:171)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:116)
	at org.compiere.apps.ProcessCtl.startProcess(ProcessCtl.java:610)
	at org.compiere.apps.ProcessCtl.run(ProcessCtl.java:360)
	at org.adempiere.webui.apps.ProcessPanel.runProcess(ProcessPanel.java:688)
	at org.adempiere.webui.apps.ProcessDialog.runProcess(ProcessDialog.java:155)
	at jdk.internal.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.zkoss.zk.ui.impl.EventProcessor.process0(EventProcessor.java:209)
	at org.zkoss.zk.ui.impl.EventProcessor.process(EventProcessor.java:141)
	at org.zkoss.zk.ui.impl.EventProcessingThreadImpl.process0(EventProcessingThreadImpl.java:519)
	at org.zkoss.zk.ui.impl.EventProcessingThreadImpl.run(EventProcessingThreadImpl.java:446)

===========> RollupWorkflow.process: java.lang.ClassNotFoundException: org.eevolution.model.impl.DefaultRoutingServiceImpl [81]
java.lang.ClassNotFoundException: org.eevolution.model.impl.DefaultRoutingServiceImpl
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.eevolution.model.RoutingServiceFactory.getRoutingService(RoutingServiceFactory.java:62)
	at org.eevolution.manufacturing.process.RollupWorkflow.doIt(RollupWorkflow.java:74)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:176)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:129)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:171)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:116)
	at org.compiere.apps.ProcessCtl.startProcess(ProcessCtl.java:610)
	at org.compiere.apps.ProcessCtl.run(ProcessCtl.java:360)
	at org.adempiere.webui.apps.ProcessPanel.runProcess(ProcessPanel.java:688)
	at org.adempiere.webui.apps.ProcessDialog.runProcess(ProcessDialog.java:155)
	at jdk.internal.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.zkoss.zk.ui.impl.EventProcessor.process0(EventProcessor.java:209)
	at org.zkoss.zk.ui.impl.EventProcessor.process(EventProcessor.java:141)
	at org.zkoss.zk.ui.impl.EventProcessingThreadImpl.process0(EventProcessingThreadImpl.java:519)
	at org.zkoss.zk.ui.impl.EventProcessingThreadImpl.run(EventProcessingThreadImpl.java:446)

2022-08-10 20:21 UTC, yamelsenih commented
> @yamelsenih , here other error when report Receipt and Issue :
> 
> ![image](https://user-images.githubusercontent.com/786968/183993141-e7b3112b-2c04-49ad-a728-62d87b66f367.png)
> 
> -----------> Msg.translate: NOT found: Altert UOM [43] -----------> MSequence.getDocumentNo: (DocType)- no record found - MDocType[50013-Manufacturing Cost Collector,DocNoSequence_ID=53272] [81] -----------> MSequence.getDocumentNo: (DocType)- no record found - MDocType[50013-Manufacturing Cost Collector,DocNoSequence_ID=53272] [81] ===========> DocumentEngine.getDoc: Doc Class invalid: org.compiere.acct.Doc_PPCostCollector (java.lang.ClassNotFoundException: org.compiere.acct.Doc_PPCostCollector) [81] ===========> DocumentEngine.getDoc: Doc Class invalid: org.compiere.acct.Doc_PPCostCollector (java.lang.ClassNotFoundException: org.compiere.acct.Doc_PPCostCollector) [81] ===========> DocumentEngine.getDoc: SELECT * FROM PP_Cost_Collector WHERE PP_Cost_Collector_ID=? AND Processed='Y' [81] UserError: Doc Class invalid: org.compiere.acct.Doc_PPCostCollector (java.lang.ClassNotFoundException: org.compiere.acct.Doc_PPCostCollector) at org.compiere.process.DocumentEngine.getDoc(DocumentEngine.java:1602) at org.compiere.process.DocumentEngine.getDoc(DocumentEngine.java:1553) at org.compiere.process.DocumentEngine.postImmediate(DocumentEngine.java:1470) at org.compiere.process.DocumentEngine.postIt(DocumentEngine.java:576) at org.compiere.process.DocumentEngine.postTheDocAndAnyPostProcessDocs(DocumentEngine.java:366) at org.compiere.process.DocumentEngine.prepareThenCompleteIt(DocumentEngine.java:353) at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:318) at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:289) at org.eevolution.manufacturing.model.MPPCostCollector.processIt(MPPCostCollector.java:293) at org.eevolution.manufacturing.model.MPPCostCollector.createCollector(MPPCostCollector.java:177) at org.eevolution.manufacturing.model.MPPOrder.createIssue(MPPOrder.java:1266) at org.eevolution.form.OrderReceiptIssue.createIssue(OrderReceiptIssue.java:323) at org.eevolution.form.WOrderReceiptIssue$1.run(WOrderReceiptIssue.java:924) at org.compiere.util.Trx.run(Trx.java:529) at org.compiere.util.Trx.run(Trx.java:497)
> 
> ===========> DocumentEngine.getDoc: SELECT * FROM PP_Cost_Collector WHERE PP_Cost_Collector_ID=? AND Processed='Y' [81] UserError: Doc Class invalid: org.compiere.acct.Doc_PPCostCollector (java.lang.ClassNotFoundException: org.compiere.acct.Doc_PPCostCollector) at org.compiere.process.DocumentEngine.getDoc(DocumentEngine.java:1602) at org.compiere.process.DocumentEngine.getDoc(DocumentEngine.java:1553) at org.compiere.process.DocumentEngine.postImmediate(DocumentEngine.java:1470) at org.compiere.process.DocumentEngine.postIt(DocumentEngine.java:576) at org.compiere.process.DocumentEngine.postTheDocAndAnyPostProcessDocs(DocumentEngine.java:366) at org.compiere.process.DocumentEngine.prepareThenCompleteIt(DocumentEngine.java:353) at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:318) at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:289) at org.eevolution.manufacturing.model.MPPCostCollector.processIt(MPPCostCollector.java:293) at org.eevolution.manufacturing.model.MPPCostCollector.createCollector(MPPCostCollector.java:177) at org.eevolution.manufacturing.model.MPPOrder.createIssue(MPPOrder.java:1266) at org.eevolution.form.OrderReceiptIssue.createIssue(OrderReceiptIssue.java:323) at org.eevolution.form.WOrderReceiptIssue$1.run(WOrderReceiptIssue.java:924) at org.compiere.util.Trx.run(Trx.java:529) at org.compiere.util.Trx.run(Trx.java:497)
> 
> -----------> MSequence.getDocumentNo: (DocType)- no record found - MDocType[50013-Manufacturing Cost Collector,DocNoSequence_ID=53272] [81] -----------> MSequence.getDocumentNo: (DocType)- no record found - MDocType[50013-Manufacturing Cost Collector,DocNoSequence_ID=53272] [81] ===========> DocumentEngine.getDoc: Doc Class invalid: org.compiere.acct.Doc_PPCostCollector (java.lang.ClassNotFoundException: org.compiere.acct.Doc_PPCostCollector) [81] ===========> DocumentEngine.getDoc: Doc Class invalid: org.compiere.acct.Doc_PPCostCollector (java.lang.ClassNotFoundException: org.compiere.acct.Doc_PPCostCollector) [81] ===========> DocumentEngine.getDoc: SELECT * FROM PP_Cost_Collector WHERE PP_Cost_Collector_ID=? AND Processed='Y' [81] UserError: Doc Class invalid: org.compiere.acct.Doc_PPCostCollector (java.lang.ClassNotFoundException: org.compiere.acct.Doc_PPCostCollector) at org.compiere.process.DocumentEngine.getDoc(DocumentEngine.java:1602) at org.compiere.process.DocumentEngine.getDoc(DocumentEngine.java:1553) at org.compiere.process.DocumentEngine.postImmediate(DocumentEngine.java:1470) at org.compiere.process.DocumentEngine.postIt(DocumentEngine.java:576) at org.compiere.process.DocumentEngine.postTheDocAndAnyPostProcessDocs(DocumentEngine.java:366) at org.compiere.process.DocumentEngine.prepareThenCompleteIt(DocumentEngine.java:353) at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:318) at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:289) at org.eevolution.manufacturing.model.MPPCostCollector.processIt(MPPCostCollector.java:293) at org.eevolution.manufacturing.model.MPPCostCollector.createCollector(MPPCostCollector.java:177) at org.eevolution.manufacturing.model.MPPOrder.createIssue(MPPOrder.java:1266) at org.eevolution.form.OrderReceiptIssue.createIssue(OrderReceiptIssue.java:323) at org.eevolution.form.WOrderReceiptIssue$1.run(WOrderReceiptIssue.java:924) at org.compiere.util.Trx.run(Trx.java:529) at org.compiere.util.Trx.run(Trx.java:497)
> 
> ===========> DocumentEngine.getDoc: SELECT * FROM PP_Cost_Collector WHERE PP_Cost_Collector_ID=? AND Processed='Y' [81] UserError: Doc Class invalid: org.compiere.acct.Doc_PPCostCollector (java.lang.ClassNotFoundException: org.compiere.acct.Doc_PPCostCollector) at org.compiere.process.DocumentEngine.getDoc(DocumentEngine.java:1602) at org.compiere.process.DocumentEngine.getDoc(DocumentEngine.java:1553) at org.compiere.process.DocumentEngine.postImmediate(DocumentEngine.java:1470) at org.compiere.process.DocumentEngine.postIt(DocumentEngine.java:576) at org.compiere.process.DocumentEngine.postTheDocAndAnyPostProcessDocs(DocumentEngine.java:366) at org.compiere.process.DocumentEngine.prepareThenCompleteIt(DocumentEngine.java:353) at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:318) at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:289) at org.eevolution.manufacturing.model.MPPCostCollector.processIt(MPPCostCollector.java:293) at org.eevolution.manufacturing.model.MPPCostCollector.createCollector(MPPCostCollector.java:177) at org.eevolution.manufacturing.model.MPPOrder.createIssue(MPPOrder.java:1266) at org.eevolution.form.OrderReceiptIssue.createIssue(OrderReceiptIssue.java:323) at org.eevolution.form.WOrderReceiptIssue$1.run(WOrderReceiptIssue.java:924) at org.compiere.util.Trx.run(Trx.java:529) at org.compiere.util.Trx.run(Trx.java:497)
> 
> -----------> MSequence.getDocumentNo: (DocType)- no record found - MDocType[50013-Manufacturing Cost Collector,DocNoSequence_ID=53272] [81] -----------> MSequence.getDocumentNo: (DocType)- no record found - MDocType[50013-Manufacturing Cost Collector,DocNoSequence_ID=53272] [81] ===========> DocumentEngine.getDoc: Doc Class invalid: org.compiere.acct.Doc_PPCostCollector (java.lang.ClassNotFoundException: org.compiere.acct.Doc_PPCostCollector) [81] ===========> DocumentEngine.getDoc: Doc Class invalid: org.compiere.acct.Doc_PPCostCollector (java.lang.ClassNotFoundException: org.compiere.acct.Doc_PPCostCollector) [81] ===========> DocumentEngine.getDoc: SELECT * FROM PP_Cost_Collector WHERE PP_Cost_Collector_ID=? AND Processed='Y' [81] UserError: Doc Class invalid: org.compiere.acct.Doc_PPCostCollector (java.lang.ClassNotFoundException: org.compiere.acct.Doc_PPCostCollector) at org.com [...]

2022-08-10 22:54 UTC, marcalwestf reviewed
.. still, testing Manufacturing Order, action=Complete: class not found:
**org.compiere.acct.Doc_PPOrder**
```
===========> DocumentEngine.getDoc: 
Doc Class invalid: org.compiere.acct.Doc_PPOrder (java.lang.ClassNotFoundException: org.compiere.acct.Doc_PPOrder) [109]
===========> DocumentEngine.getDoc: 
SELECT * FROM PP_Order WHERE PP_Order_ID=? AND Processed='Y' [109]
UserError: Doc Class invalid: org.compiere.acct.Doc_PPOrder (java.lang.ClassNotFoundException: org.compiere.acct.Doc_PPOrder)
at org.compiere.process.DocumentEngine.getDoc(DocumentEngine.java:1602)
at org.compiere.process.DocumentEngine.getDoc(DocumentEngine.java:1553)
at org.compiere.process.DocumentEngine.postImmediate(DocumentEngine.java:1470)
at org.compiere.process.DocumentEngine.postIt(DocumentEngine.java:576)
at org.compiere.process.DocumentEngine.postTheDocAndAnyPostProcessDocs
(DocumentEngine.java:366)
at org.compiere.process.DocumentEngine.prepareThenCompleteIt(DocumentEngine.java:353)
at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:318)
at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:289)
at org.eevolution.manufacturing.model.MPPOrder.processIt(MPPOrder.java:533)
at org.compiere.wf.MWFActivity.performWork(MWFActivity.java:861)
```

2022-08-10 23:09 UTC, marcalwestf reviewed
### Test # 9: Libero
- Component Check -> OK
- Report Manufacturing Orders Review -> OK
- Execute Order Receipt & Issue  -> **ERROR**:  class _org.compiere.acct.Doc_PPCostCollector_ not found
```
-----------> MSequence.getDocumentNo: (DocType)- no record found - MDocType[50013-Manufacturing Cost Collector,DocNoSequence_ID=53272] [20]
===========> DocumentEngine.getDoc: Doc Class invalid: org.compiere.acct.Doc_PPCostCollector (java.lang.ClassNotFoundException: org.compiere.acct.Doc_PPCostCollector) [20]
===========> DocumentEngine.getDoc: SELECT * FROM PP_Cost_Collector WHERE PP_Cost_Collector_ID=? AND Processed='Y' [20]
UserError: Doc Class invalid: org.compiere.acct.Doc_PPCostCollector (java.lang.ClassNotFoundException: org.compiere.acct.Doc_PPCostCollector)
	at org.compiere.process.DocumentEngine.getDoc(DocumentEngine.java:1602)
	at org.compiere.process.DocumentEngine.getDoc(DocumentEngine.java:1553)
	at org.compiere.process.DocumentEngine.postImmediate(DocumentEngine.java:1470)
	at org.compiere.process.DocumentEngine.postIt(DocumentEngine.java:576)
	at org.compiere.process.DocumentEngine.postTheDocAndAnyPostProcessDocs(DocumentEngine.java:366)
	at org.compiere.process.DocumentEngine.prepareThenCompleteIt(DocumentEngine.java:353)
	at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:318)
	at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:289)
	at org.eevolution.manufacturing.model.MPPCostCollector.processIt(MPPCostCollector.java:293)
	at org.eevolution.manufacturing.model.MPPCostCollector.createCollector(MPPCostCollector.java:177)
	at org.eevolution.manufacturing.model.MPPOrder.createIssue(MPPOrder.java:1266)
	at org.eevolution.form.OrderReceiptIssue.createIssue(OrderReceiptIssue.java:323)
	at org.eevolution.form.VOrderReceiptIssue$1.run(VOrderReceiptIssue.java:893)
```

2022-08-10 23:38 UTC, marcalwestf commented
here's the error, which is reproduced, even after applying the XML file:
In class `DocumentEngine`, the  package is set to `org.compiere.acct`:

![imagen](https://user-images.githubusercontent.com/1789408/184040917-28741dab-ac90-4bca-946a-650524956d6a.png)

2022-08-11 14:07 UTC, marcalwestf commented
@yamelsenih  the error persists even if the tests are done with the seed database that is generated by the Github action.
This includes the latest XML of the PR.

2022-08-11 16:00 UTC, marcalwestf commented
### Test # 10: WMS
- Warehouse Area Type -> OK
- Warehouse Section Type -> OK
- Warehouse Structure -> OK
- In/Outbound Rule -> OK
- In/Outbound Strategy -> OK
- In/Outbound Definition -> OK
- Outbound Order -> OK
- Generate Outbound Order Based On Demand -> OK
- Generate Outbound Order Based On Sales Order -> OK
- Generate Outbound (Sales Order/Distribution Order) -> ERROR `java.lang.ClassNotFoundException: org.spin.wms.form.VOutBoundOrder`
![Selection_310](https://user-images.githubusercontent.com/1789408/184177611-5e5f074c-b29c-4bd0-9416-2bb5423fc32f.png)

2022-08-11 20:15 UTC, yamelsenih commented
> here's the error, which is reproduced, even after applying the XML file: In class `DocumentEngine`, the package is set to `org.compiere.acct`:
> 
> ![imagen](https://user-images.githubusercontent.com/1789408/184040917-28741dab-ac90-4bca-946a-650524956d6a.png)

Hi @marcalwestf this was resolved yet

2022-08-11 20:23 UTC, yamelsenih commented
> ### Test # 10: WMS
> * Warehouse Area Type -> OK
> * Warehouse Section Type -> OK
> * Warehouse Structure -> OK
> * In/Outbound Rule -> OK
> * In/Outbound Strategy -> OK
> * In/Outbound Definition -> OK
> * Outbound Order -> OK
> * Generate Outbound Order Based On Demand -> OK
> * Generate Outbound Order Based On Sales Order -> OK
> * Report Outbound Order delivery schedule -> OK
> * Report Outbound Order Detail -> OK
> * Scheduling of the Demands -> OK
> * Generate Outbound (Sales Order/Distribution Order) -> ERROR `java.lang.ClassNotFoundException: org.spin.wms.form.VOutBoundOrder`
>   ![Selection_310](https://user-images.githubusercontent.com/1789408/184177611-5e5f074c-b29c-4bd0-9416-2bb5423fc32f.png)

Hi @marcalwestf this form is no supported for Swing UI, just was created for ZK
![Screenshot from 2022-08-11 16-20-50](https://user-images.githubusercontent.com/2333092/184235491-4ab6478d-9a7e-472a-bfbe-7b312475e9ad.png)

2022-08-11 21:34 UTC, marcalwestf commented
@yamelsenih I'd like to test this pull request on ZK based on an installation, but I cannot run an installation because of the following reasons:
- I cannot run `gradle build`
- `ANT run build` from IDE delivers en error
- `Gradle build` on Github Actions delivers error

![imagen](https://user-images.githubusercontent.com/1789408/184245856-09127988-902d-4415-82ce-a353369e2801.png)
![imagen](https://user-images.githubusercontent.com/1789408/184245945-594fb580-6ea3-4567-81b2-6c1e9152dc5b.png)

2022-08-11 23:28 UTC, yamelsenih commented
> @yamelsenih I'd like to test this pull request on ZK based on an installation, but I cannot run an installation because of the following reasons:
> 
> * I cannot run `gradle build`
> * `ANT run build` from IDE delivers en error
> * `Gradle build` on Github Actions delivers error
> 
> ![imagen](https://user-images.githubusercontent.com/1789408/184245856-09127988-902d-4415-82ce-a353369e2801.png) ![imagen](https://user-images.githubusercontent.com/1789408/184245945-594fb580-6ea3-4567-81b2-6c1e9152dc5b.png)

Hi @marcalwestf the problem is a bad unit test. I will check it tomorrow

2022-08-13 01:27 UTC, marcalwestf reviewed
Test on ZK
- build with ANT  -> OK
- install Adempiere with Tomcat  -> OK
- run Adempiere on Tomcat -> OK
- various tests (purchase cycle, sales cycle, material movement, physical inventory) -> OK
- Libero tests (manuf. order, component checks, receipt & issue, BOM/workflow cost roll up, many reports) -> OK
- forecast tests -> OK

Errors
- build with gradle -> ERROR (still). Same as explained before.
- production ligth test -> ERROR (still). See details under Test # 4 on this thread ("value" does not exist)
- Libero test: Report Cost BOM Multi Level Review -> ERROR (**new**): class not found **org.eevolution.report.CostBillOfMaterial**

![Selection_321](https://user-images.githubusercontent.com/1789408/184463289-72154728-513b-40e5-bcf8-bf413fbbbf78.png)


```
-----------> ProcessUtil.startJavaProcess: org.eevolution.report.CostBillOfMaterial [42]
java.lang.ClassNotFoundException: org.eevolution.report.CostBillOfMaterial
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:141)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:116)
	at org.compiere.apps.ProcessCtl.startProcess(ProcessCtl.java:610)
	at org.compiere.apps.ProcessCtl.run(ProcessCtl.java:360)
```

2022-08-13 17:23 UTC, yamelsenih commented
> org.eevolution.report.CostBillOfMaterial

Hi @marcalwestf this was resolved. Please remove your migration applied and import it from new commit.

2022-08-13 17:29 UTC, marcalwestf commented
Thanks @yamelsenih I will check it out.

2022-08-14 00:57 UTC, marcalwestf reviewed
Libero test: Report _Cost BOM Multi Level Review_ -> **OK**

2022-08-15 16:18 UTC, yamelsenih commented
> * Production

Hi @marcalwestf this error was resolved yet

2022-08-15 19:23 UTC, marcalwestf reviewed
- A _Production Batch_ was created, prepared, and completed -> OK
- A _Production_ completed using the `button` on Swing-> OK
![imagen](https://user-images.githubusercontent.com/1789408/184702104-093fbb0d-bb70-46ac-91c7-ddd230be51fc.png)
- A _Production_ completed using the `icon` (toolbar) on Swing->` java.lang.ClassNotFoundException: org.compiere.process.ProductionProcess`
![imagen](https://user-images.githubusercontent.com/1789408/184702401-3b77f7b1-09db-42b1-b3dc-f8dea87299c4.png)

2022-08-16 14:03 UTC, yamelsenih commented
Hi @marcalwestf the process "Process Production" is no longer supported because already exists the workflow for Production, this process was deprecated and instead just should run document action with process instead complete action

2022-08-16 14:19 UTC, yamelsenih commented
> * A _Production Batch_ was created, prepared, and completed -> OK
> * A _Production_ completed using the `button` on Swing-> OK
>   ![imagen](https://user-images.githubusercontent.com/1789408/184702104-093fbb0d-bb70-46ac-91c7-ddd230be51fc.png)
> * A _Production_ completed using the `icon` (toolbar) on Swing->` java.lang.ClassNotFoundException: org.compiere.process.ProductionProcess`
>   ![imagen](https://user-images.githubusercontent.com/1789408/184702401-3b77f7b1-09db-42b1-b3dc-f8dea87299c4.png)

Hi @marcalwestf these process are deprecated here: https://github.com/adempiere/adempiere/pull/3966/commits/b032393fd8d68509a5d3b4ae1c4b2c0c03534799

Please remove current XML and import it from source

2022-08-16 20:59 UTC, marcalwestf commented
@yamelsenih  Yamel, concerning the gradle error: 
### Gradle build sucess
At last, I was able to get the exact result as the action when calling `gradle build`:
![imagen](https://user-images.githubusercontent.com/1789408/184979590-b1641f0c-18da-443c-a2a6-32c6ee6b31e0.png)

The reason: using different JDKs like _zulu-jdk11.0.15_, or _java-11-openjdk-amd64_ there were errors thrown.
With _jdk-11.0.11+9_, and _jdk-11.0.11_ instead, I could run `gradle build` successfully. I ignore if there are more; in the action, _jdk-11.0.11+8_ is used.
We thus, must be very careful wich JDK we use to build.

### Correction of typo
I notice, in all build.gradle files the variable name is `ADEMIERE_LIBRARY_VERSION` instead of `ADEMPIERE_LIBRARY_VERSION`:
![imagen](https://user-images.githubusercontent.com/1789408/184895782-f4e77b11-eab8-4d83-ab56-1d7c977ce44d.png)

This should be modified in all gradle.build files which refer to this variable to `ADEMPIERE_LIBRARY_VERSION`, because users might try to write the correct name (=ADEMPIERE) and this would lead to errors.

### .gitignore for Gradle
Also, the .gradle directory should be included in the .gitignore file, so it files are not considered to be pushed, which confuses otherwise:
![imagen](https://user-images.githubusercontent.com/1789408/184983440-de9f7d99-906b-45b4-b0e2-32bd75ecdedf.png)

### Question
Last, but not least, I notice that `gradle build` compiles, but it doesn't create packages nor the binary as ANT does, is it correct?

2022-08-16 21:28 UTC, marcalwestf commented
@yamelsenih  about the error at Production: the error is thrown when you click on the icon, as you can see in the following image.
The process dialog is shown and the complete action works well, nothwithstanding.
![Selection_327-modifieda](https://user-images.githubusercontent.com/1789408/184987924-7f8f810c-0926-4f2c-b933-ff8ecdd1cce2.png)

2022-08-17 00:08 UTC, yamelsenih commented
> @yamelsenih Yamel, concerning the gradle error:
> 
> ### Gradle build sucess
> At last, I was able to get the exact result as the action when calling `gradle build`: ![imagen](https://user-images.githubusercontent.com/1789408/184979590-b1641f0c-18da-443c-a2a6-32c6ee6b31e0.png)
> 
> The reason: using different JDKs like _zulu-jdk11.0.15_, or _java-11-openjdk-amd64_ there were errors thrown. With _jdk-11.0.11+9_, and _jdk-11.0.11_ instead, I could run `gradle build` successfully. I ignore if there are more; in the action, _jdk-11.0.11+8_ is used. We thus, must be very careful wich JDK we use to build.
> 
> ### Correction of typo
> I notice, in all build.gradle files the variable name is `ADEMIERE_LIBRARY_VERSION` instead of `ADEMPIERE_LIBRARY_VERSION`: ![imagen](https://user-images.githubusercontent.com/1789408/184895782-f4e77b11-eab8-4d83-ab56-1d7c977ce44d.png)
> 
> This should be modified in all gradle.build files which refer to this variable to `ADEMPIERE_LIBRARY_VERSION`, because users might try to write the correct name (=ADEMPIERE) and this would lead to errors.
> 
> ### .gitignore for Gradle
> Also, the .gradle directory should be included in the .gitignore file, so it files are not considered to be pushed, which confuses otherwise: ![imagen](https://user-images.githubusercontent.com/1789408/184983440-de9f7d99-906b-45b4-b0e2-32bd75ecdedf.png)
> 
> ### Question
> Last, but not least, I notice that `gradle build` compiles, but it doesn't create packages nor the binary as ANT does, is it correct?

Hi @marcalwestf thanks, hahaha was me at 3:00 AM.

This was resolved here: https://github.com/adempiere/adempiere/pull/3966/commits/305f56041b0e591246b5c33ae58f62e0f081af9a

2022-08-17 00:09 UTC, yamelsenih commented
> @yamelsenih Yamel, I loaded and applied the XML file. The changes you made are OK and improve the usability.
> 
> About the error at Production: the error is thrown when you click on the icon, as you can see in the following image. The process dialog is shown and the complete action works well, nothwithstanding. ![Selection_327-modifieda](https://user-images.githubusercontent.com/1789408/184987924-7f8f810c-0926-4f2c-b933-ff8ecdd1cce2.png)

Hi @marcalwestf this was resolved here: https://github.com/adempiere/adempiere/pull/3966/commits/b2c8e0eebfaa85a11c2a9b040e650b2ae8c21057

The current functionality is unsupported for fields disabled or hidden

2022-08-17 07:18 UTC, marcalwestf commented
hi @yamelsenih , at last, all the tests were positive.
From my side, this PR can be accepted.

2022-08-17 13:05 UTC, marcalwestf approved these changes
After many tests and corrections,  this PR doesn't throw any exception of the type ClassNotFound nor causes malfunctions.

2022-08-17 18:00 UTC, marcalwestf commented
FYI:
Steps to run Gradle
- install latest **Gradle** (as of today: 7.5.1)
- install **JDK 11**, but beware that for example zulu-jdk11.0.15, or java-11-openjdk-amd64 delivered errors on my test , but  jdk-11.0.11+9, and jdk-11.0.11 yielded no error.
- on the console, set and export variable ADEMPIERE_LIBRARY_VERSION to any value (e.g. `export ADEMPIERE_LIBRARY_VERSION=1.0.0`)
- on the console, go to the repository root directory (`cd ...`)
- on the console, run `gradle build`

2022-08-19 22:01 UTC, e-Evolution commented
@yamelsenih Yamel I found a potential problem, it is not correct to replace an MModel class with X_Model since the X_Model classes do not contain the business logic after and before saving and/or deleting.

This may be that using the X_ class changes the behavior because it is not applying the business logic required in the MModel class.

X_Model classes can be used for reading only but not for using the save method:

Here is an example in the class with this problem:

AbstractCostingMethod.java

Please check any other refactory where you applied this procedure because it is not suitable.

![image](https://user-images.githubusercontent.com/786968/185712850-fcdfcdb6-8e27-44e6-b173-abbc195c00be.png)



I also realize that the code of the TestDocumentEngine.java class was removed from a test, the test does not pass and it is necessary to fix it later, do not remove the code, it is better to comment it and put a TODO: in the comment, we can ask Mike to review it for the behavior of the test since he was the one who designed that test.


it's not good to sweep code under the rug :-)

In the StandardCostingMethod.java class, code was removed although some utility classes were created, I could not find anywhere how that business logic that was executed before is now executed in this class.

In special the variance cost standard 


```
		if (model instanceof MPPCostCollector)
		{
			MPPCostCollector cc = (MPPCostCollector) model;
			if (MPPCostCollector.COSTCOLLECTORTYPE_MethodChangeVariance.equals(cc.getCostCollectorType())) {
				createMethodVariances(cc);
			} else if (MPPCostCollector.COSTCOLLECTORTYPE_UsegeVariance.equals(cc.getCostCollectorType())) {
				createUsageVariances(cc);
			} else if (MPPCostCollector.COSTCOLLECTORTYPE_RateVariance.equals(cc.getCostCollectorType())) {
				createRateVariances(cc);
			} else if (MPPCostCollector.COSTCOLLECTORTYPE_MixVariance.equals(cc.getCostCollectorType())) {
				; // no implement
			}
		}
```

![image](https://user-images.githubusercontent.com/786968/185712167-3760c472-14e8-4560-94fa-36a5f41d74f1.png)



On the other hand, I see very well that all the callouts have been changed to a new package called controller, which seems correct to me, but since this is being done and the packages have been restructured, it seems very important to me to use the same pattern for all the callouts. that were moved from their current package, taking advantage of the fact that you already have the XML that changes the path of the package, it would be good if they all use the same pattern.


![image](https://user-images.githubusercontent.com/786968/185712199-c46ffc03-764a-4846-b12d-3a138c869cbf.png)


So the moment these changes are applied and my question is answered I can complete the merge.

on the other hand, I want to thank you for your enormous effort in this great challenge it was not easy, but you did it, congratulations

2022-09-04 13:53 UTC, marcalwestf commented
@yamelsenih, @e-Evolution  about the gradle files: in the gradle documentation (https://docs.gradle.org/current/userguide/java_plugin.html#sec:java-extension) and other explanations (e.g. https://www.baeldung.com/gradle-sourcecompatiblity-vs-targetcompatibility), there is a welll-defined description of using _sourceCompatibility_ and _targetCompatibility_.

If we take into account that we compile ADempiere with JDK 11, but can execute with either JDK 11 or JDK 17, I think, the configuration should be 
```
sourceCompatibility = 1.11
targetCompatibility = 1.17
```

This would allow us to compile up to JDK 11, and run with no less than JDK 17.
What do you think?

2022-09-20 21:16 UTC, e-Evolution approved these changes
I finished the pending refactory in code  and enhancements : 

- Change package name from service to services to improve package names in ADempiere's DSL
- Add business functionality for the calculation of variations in the standard cost method that was removed in previous commits
- Change package name for Fixed Assets from FA to asset
- Normalization of names for Callout of Assets, these were moved to the controller package
- Normalization of process names and implementation using the abstract class
- Move domino models to package org.adempiere.core.domains.models
- Set the application dictionary items to the entity type for Fixed Assets
- Fix the XML Script to define Release No and change the packages in the application dictionary

2022-09-20 21:16 UTC, merged