Bug Fix Missing trx in workflow query outdated PO data
adempiere/adempiere pull request #4267
Opened 2023-12-07 21:44 UTC by rcapecce

Fix #4266

2023-12-12 04:06 UTC, marcalwestf commented
@rcapecce this is an insignificant matter, but I suppose you wanted the commit c4aa1502014951ca90f0eeb67ad8deefbe77d3a7 to be made on class MWFProcess, instead of MOrder ;)

Starting to test your PR.

2023-12-12 05:01 UTC, marcalwestf approved these changes
**To reproduce the error**, the steps described in the issue were completed.
1.- An Order was created and it was indeed completed without running through the approval workflow defined:
![image](https://github.com/adempiere/adempiere/assets/1789408/60aa412a-ab75-461f-94f6-6a3532245f33)


**To reproduce the bug fix**, the steps described in the issue were completed.
1.- After executing the _Complete_ action, the order is now not in the status "Completed", but  "In Progress"
![image](https://github.com/adempiere/adempiere/assets/1789408/8128df40-9805-48c4-9d78-817b592c9be4)


2.- The Order has to be accepted by User "GardenUser"
![image](https://github.com/adempiere/adempiere/assets/1789408/a38dd0fb-7934-4240-b1c2-7f8c63bcde2f)

3.- Result of Approval:
![image](https://github.com/adempiere/adempiere/assets/1789408/a1415969-7cbd-4bd5-b83d-c2439db1d41f)

4.- Result at Order: document status became _Approved_ after _In Progress_ and _Completed_ after _Approved:_
![image](https://github.com/adempiere/adempiere/assets/1789408/9906e22f-771b-4590-88c4-25f3935af85e)


All tests passed; pull request accepted

2023-12-12 21:49 UTC, marcalwestf commented
This pull request has been tested and accepted; it can be merged, but it is waiting for older pull requests to be merged.

2023-12-13 00:56 UTC, EdwinBetanc0urt requested changes

2023-12-13 00:56 UTC, EdwinBetanc0urt commented on base/src/org/compiere/model/MOrder.java
> + *		<a href="https://github.com/adempiere/adempiere/issues/4266">
Hi @rcapecce, is there a reason to modify the comment in the `MOrder` class? I think the comment should be moved to the `MWFProcess` class.

2023-12-13 02:40 UTC, e-Evolution commented
@rcapecce Hi Raul

I have reviewed the logic and it is not clear to me the sequence of your nodes in your workflow. Given that the transaction is in progress, it is correct that you cannot evaluate the C_DocType_ID field because that value has not yet been committed since it is part of the transaction not completed.

Can set here you flow the your workflow as :

![image](https://github.com/adempiere/adempiere/assets/786968/3405f65e-89e4-4b18-95cb-8abb95b3becc)

Every time a step is processed, the PO of the document should be uploaded before processing, so I consider that the problem is that it is being evaluated against a stale PO, when you mention that the PO was uploaded for a null transaction I do not understand how it can happen if The doc action that executes the process to complete the document adds a transaction so it should not be null and if it is I believe from the MWFActivity call it assigns a transaction, so again it should not be null, if it is that is the problem, we must identify why the document instance is loaded as null.

In any case, your validation in the workflow should be with C_DocTypeTarget_ID which has a value before the node (DocPrepare) is called. I think it is not valid to use C_DocType_ID when the prepareIt() method that sets that value is just being processed.

kind regards
Victor

2023-12-13 12:22 UTC, rcapecce commented on base/src/org/compiere/model/MOrder.java
> + *		<a href="https://github.com/adempiere/adempiere/issues/4266">
oh my bad, I have fixed this

2023-12-13 12:23 UTC, rcapecce commented
> @rcapecce this is an insignificant matter, but I suppose you wanted the commit [c4aa150](https://github.com/adempiere/adempiere/commit/c4aa1502014951ca90f0eeb67ad8deefbe77d3a7) to be made on class MWFProcess, instead of MOrder ;)
> 
> Starting to test your PR.

Yes, fixed! Thank you @marcalwestf

2023-12-13 15:10 UTC, rcapecce commented
> @rcapecce Hi Raul
> 
> I have reviewed the logic and it is not clear to me the sequence of your nodes in your workflow. Given that the transaction is in progress, it is correct that you cannot evaluate the C_DocType_ID field because that value has not yet been committed since it is part of the transaction not completed.
> 
> Can set here you flow the your workflow as :
> 
> ![image](https://private-user-images.githubusercontent.com/786968/290058152-3405f65e-89e4-4b18-95cb-8abb95b3becc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NzE4MjMsIm5iZiI6MTcwMjQ3MTUyMywicGF0aCI6Ii83ODY5NjgvMjkwMDU4MTUyLTM0MDVmNjVlLTg5ZTQtNGIxOC05NWNiLThhYmI5NWIzYmVjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QxMjQ1MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMjI1MjdjZmU1ZjQ2OTUwOWI0OWZiMzI2Y2NhOGZhY2NlYTIwZjk1ZjFiZjhkOGJkZDgxZGNiMDE3NGZhYzE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5R8XFuKhvUcS3zgaiWuu4YNllQx6gs5PTXvAU7CLumc)
> 
> Every time a step is processed, the PO of the document should be uploaded before processing, so I consider that the problem is that it is being evaluated against a stale PO, when you mention that the PO was uploaded for a null transaction I do not understand how it can happen if The doc action that executes the process to complete the document adds a transaction so it should not be null and if it is I believe from the MWFActivity call it assigns a transaction, so again it should not be null, if it is that is the problem, we must identify why the document instance is loaded as null.
> 
> In any case, your validation in the workflow should be with C_DocTypeTarget_ID which has a value before the node (DocPrepare) is called. I think it is not valid to use C_DocType_ID when the prepareIt() method that sets that value is just being processed.
> 
> kind regards Victor

Hi @e-Evolution 

I am not saying that the PO information is not being loaded in each step, what I am commenting here is that only in the section where the conditions of the node to advance are evaluated, that is where the transaction reaches null, only at the time of evaluating the conditions.

Here https://github.com/adempiere/adempiere/blob/5fc84c4f87de754c6b2cc715e4d5c779c387ad5f/base/src/org/compiere/wf/MWFNodeNext.java#L158 when obtains the PO to evaluate, the trx is missing and obtanins a data out of the current transaction.

Then, the action of the prepareIt() node ends and saves the savepoint, but the conditions when loaded the PO from the database without a transaction do not see the data reflected

2023-12-13 19:22 UTC, merged

2023-12-14 08:31 UTC, marcalwestf commented
a modification like this should have included a whole workflow test after the actual PR test.

To make sure the workflows weren't damaged, I also tested the following cases.

Prepare, complete and void of the following documents:
- Requisition
- Purchase Order
- Purchase Invoice
- Material Receipt
- Sales Order
- Sales Invoice
- Material Issue

2023-12-14 13:22 UTC, rcapecce commented
I understand that the workflow does not apply to processes but to make sure I carried out the following test with the base code and with the PR, obtaining that all the documents were Completed, those that had a flow and those that did not.
The process used was SB Process Batch Orders.